<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Giovanny Covarrubias-Pazaran" />

<meta name="date" content="2019-08-24" />

<title>Quantitative genetics using the sommer package</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; min-height: 1.25em; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; }
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
@media screen {
a.sourceLine::before { text-decoration: underline; color: initial; }
}
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.bn { color: #40a070; } /* BaseN */
code span.fl { color: #40a070; } /* Float */
code span.ch { color: #4070a0; } /* Char */
code span.st { color: #4070a0; } /* String */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.ot { color: #007020; } /* Other */
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.fu { color: #06287e; } /* Function */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code span.cn { color: #880000; } /* Constant */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.ss { color: #bb6688; } /* SpecialString */
code span.im { } /* Import */
code span.va { color: #19177c; } /* Variable */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.op { color: #666666; } /* Operator */
code span.bu { } /* BuiltIn */
code span.ex { } /* Extension */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.at { color: #7d9029; } /* Attribute */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' || rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#header {
text-align: center;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; }  code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>

</head>

<body>




<h1 class="title toc-ignore">Quantitative genetics using the sommer package</h1>
<h4 class="author"><em>Giovanny Covarrubias-Pazaran</em></h4>
<h4 class="date"><em>2019-08-24</em></h4>



<p>The sommer package was developed to provide R users a powerful and reliable multivariate mixed model solver for different genetic and non-genetic analysis in diploid and polyploid organisms. This package allows the user to estimate variance components for a mixed model with the advantage of specifying the variance-covariance structure of the random effects, specify heterogeneous variances, and obtain other parameters such as BLUPs, BLUEs, residuals, fitted values, variances for fixed and random effects, etc. The core algorithms of the package are coded in C++ using the Armadillo library to opmitime dense matrix operations common in the derect-inversion algorithms.</p>
<p>The package is focused on problems of the type p &gt; n related to genomic prediction (hybrid prediction &amp; genomic selection) and GWAS analysis, although any general mixed model can be fitted as well. The package provides kernels to estimate additive (<code>A.mat</code>), dominance (<code>D.mat</code>), and epistatic (<code>E.mat</code>) relationship matrices that have been shown to increase prediction accuracy under certain scenarios or simply to estimate the variance components of such. The package provides flexibility to fit other genetic models such as full and half diallel models as well.</p>
<p>Vignettes aim to provide several examples in how to use the sommer package under different scenarios. We will spend the rest of the space providing examples for:</p>
<ol style="list-style-type: decimal">
<li>Heritability (<span class="math inline">\(h^2\)</span>) calculation</li>
<li>Specifying heterogeneous variances in mixed models</li>
<li>Using the pin calculator</li>
<li>Half and full diallel designs (using the overlay)</li>
<li>Genomic selection (predicting mendelian sampling)
<ul>
<li>GBLUP</li>
<li>rrBLUP</li>
</ul></li>
<li>Single cross prediction (hybrid prediction)</li>
<li>Spatial modeling (using the 2-dimensional splines)</li>
<li>Multivariate genetic models and genetic correlations</li>
<li>Final remarks</li>
</ol>
<div id="background" class="section level2">
<h2>Background</h2>
<p>The core of the package the <code>mmer</code>function which solve the mixed model equations. The functions are an interface to call the <code>NR</code> Direct-Inversion Newton-Raphson or Average Information (Tunnicliffe 1989; Gilmour et al. 1995; Lee et al. 2016). Since version 2.0 sommer can handle multivariate models. Following Maier et al. (2015), the multivariate (and by extension the univariate) mixed model implemented has the form:</p>
<p><br></p>
<p><span class="math inline">\(y_1 = X_1\beta_1 + Z_1u_1 + \epsilon_1\)</span> <span class="math inline">\(y_2 = X_2\beta_2 + Z_2u_2 + \epsilon_2\)</span> … <span class="math inline">\(y_i = X_i\beta_i + Z_iu_i + \epsilon_i\)</span></p>
<p><br></p>
<p>where <span class="math inline">\(y_i\)</span> is a vector of trait phenotypes, <span class="math inline">\(\beta_i\)</span> is a vector of fixed effects, <span class="math inline">\(u_i\)</span> is a vector of random effects for individuals and <span class="math inline">\(e_i\)</span> are residuals for trait ‘i’ (i = 1, …, t). The random effects (<span class="math inline">\(u_1\)</span> … <span class="math inline">\(u_i\)</span> and <span class="math inline">\(e_i\)</span>) are assumed to be normally distributed with mean zero. X and Z are incidence matrices for fixed and random effects respectively. The distribution of the multivariate response and the phenotypic variance covariance (V) are:</p>
<p><br></p>
<p><span class="math inline">\(Y = X\beta + ZU + \epsilon_i\)</span></p>
<p><br></p>
<p>Y ~ MVN(<span class="math inline">\(X\beta\)</span>, V)</p>
<p><br></p>
<p><span class="math display">\[\mathbf{Y} = \left[\begin{array}
{r}
y_1 \\
y_2 \\
... \\
y_t \\
\end{array}\right]
\]</span></p>
<p><br></p>
<p><span class="math display">\[\mathbf{X} = \left[\begin{array}
{rrr}
X_1 &amp; ... &amp; ... \\
\vdots &amp; \ddots &amp; \vdots\\
... &amp; ... &amp; X_t \\
\end{array}\right]
\]</span></p>
<p><br></p>
<p><span class="math display">\[\mathbf{V} = \left[\begin{array}
{rrr}
Z_1 K{\sigma^2_{g_{1}}} Z_1' + H{\sigma^2_{\epsilon_{1}}} &amp; ... &amp; Z_1 K{\sigma_{g_{1,t}}} Z_t' + H{\sigma_{\epsilon_{1,t}}}\\
 \vdots &amp; \ddots &amp; \vdots\\
Z_1 K{\sigma_{g_{1,t}}} Z_t' + H{\sigma_{\epsilon_{1,t}}} &amp; ... &amp; Z_t K{\sigma^2_{g_{t}}} Z_t' + H{\sigma^2_{\epsilon_{t}}} \\
\end{array}\right]
\]</span></p>
<p><br></p>
<p>where K is the relationship or covariance matrix for the kth random effect (u=1,…,k), and R=I is an identity matrix for the residual term. The terms <span class="math inline">\(\sigma^2_{g_{i}}\)</span> and <span class="math inline">\(\sigma^2_{\epsilon_{i}}\)</span> denote the genetic (or any of the kth random terms) and residual variance of trait ‘i’, respectively and <span class="math inline">\(\sigma_{g_{_{ij}}}\)</span> and <span class="math inline">\(\sigma_{\epsilon_{_{ij}}}\)</span> the genetic (or any of the kth random terms) and residual covariance between traits ‘i’ and ‘j’ (i=1,…,t, and j=1,…,t). The algorithm implemented optimizes the log likelihood:</p>
<p><br></p>
<p><span class="math inline">\(logL = 1/2 * ln(|V|) + ln(X'|V|X) + Y'PY\)</span></p>
<p><br></p>
<p>where || is the determinant of a matrix. And the REML estimates are updated using a Newton optimization algorithm of the form:</p>
<p><br></p>
<p><span class="math inline">\(\theta^{k+1} = \theta^{k} + (H^{k})^{-1}*\frac{dL}{d\sigma^2_i}|\theta^k\)</span></p>
<p><br></p>
<p>Where, <span class="math inline">\(\theta\)</span> is the vector of variance components for random effects and covariance components among traits, <span class="math inline">\(H^{-1}\)</span> is the inverse of the Hessian matrix of second derivatives for the kth cycle, <span class="math inline">\(\frac{dL}{d\sigma^2_i}\)</span> is the vector of first derivatives of the likelihood with respect to the variance-covariance components. The Eigen decomposition of the relationship matrix proposed by Lee and Van Der Werf (2016) was included in the Newton-Raphson algorithm to improve time efficiency. Additionally, the popular pin function to estimate standard errors for linear combinations of variance components (i.e. heritabilities and genetic correlations) was added to the package as well.</p>
<p>Please refer to the canonical papers listed in the Literature section to check how the algorithms work. We have tested widely the methods to make sure they provide the same solution when the likelihood behaves well but for complex problems they might lead to slightly different answers. If you have any concern please contact me at <a href="mailto:cova_ruber@live.com.mx">cova_ruber@live.com.mx</a>.</p>
<p>In the following section we will go in detail over several examples on how to use mixed models in univariate and multivariate case and their use in quantitative genetics.</p>
<p><br></p>
</div>
<div id="marker-and-non-marker-based-heritability-calculation" class="section level2">
<h2>1) Marker and non-marker based heritability calculation</h2>
<p>The heritability is one of the most popular parameters among the breeding and genetics community because of the insight that provides in the inheritance of the trait. The heritability is usually estimated as narrow sense (<span class="math inline">\(h^2\)</span>; only additive variance in the numerator <span class="math inline">\(\sigma^2_A\)</span>), and broad sense (<span class="math inline">\(H^2\)</span>; all genetic variance in the numerator <span class="math inline">\(\sigma^2_G\)</span>).</p>
<p>In a classical breeding experiment with no molecular markers, special designs are performed to estimate and disect the additive (<span class="math inline">\(\sigma^2_A\)</span>) and non-additive (i.e. dominance <span class="math inline">\(\sigma^2_D\)</span>) variance along with environmental variability. Designs such as generation analysis, North Carolina designs are used to disect <span class="math inline">\(\sigma^2_A\)</span> and <span class="math inline">\(\sigma^2_D\)</span> to estimate the narrow sense heritability (<span class="math inline">\(h^2\)</span>). When no special design is available we can still disect the genetic variance (<span class="math inline">\(\sigma^2_G\)</span>) and estimate the broad sense heritability. In this first example we will show the broad sense estimation which doesn’t use covariance structures for the genotipic effect (i.e. genomic or additive relationship matrices). For big models with no covariance structures, sommer’s direct inversion is a bad idea to use but we will show anyways how to do it, but keep in mind that for very sparse models we recommend using the lmer function from the lme4 package or any other package using MME-based algorithms (i.e. asreml-R).</p>
<p>The following dataset has 41 potato lines evaluated in 5 locations across 3 years in an RCBD design. We show how to fit the model and extract the variance components to calculate the <span class="math inline">\(h^2\)</span>.</p>
<pre class="sourceCode r" id="cb1"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(sommer)</a></code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: MASS</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Loading required package: crayon</code></pre>
<pre class="sourceCode r" id="cb6"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">data</span>(DT_example)</a>
<a class="sourceLine" id="cb6-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_example</a>
<a class="sourceLine" id="cb6-3" data-line-number="3">A &lt;-<span class="st"> </span>A_example</a>
<a class="sourceLine" id="cb6-4" data-line-number="4"></a>
<a class="sourceLine" id="cb6-5" data-line-number="5">ans1 &lt;-<span class="st"> </span><span class="kw">mmer</span>(Yield<span class="op">~</span><span class="dv">1</span>,</a>
<a class="sourceLine" id="cb6-6" data-line-number="6">             <span class="dt">random=</span> <span class="op">~</span><span class="st"> </span>Name <span class="op">+</span><span class="st"> </span>Env <span class="op">+</span><span class="st"> </span>Env<span class="op">:</span>Name <span class="op">+</span><span class="st"> </span>Env<span class="op">:</span>Block,</a>
<a class="sourceLine" id="cb6-7" data-line-number="7">             <span class="dt">rcov=</span> <span class="op">~</span><span class="st"> </span>units,</a>
<a class="sourceLine" id="cb6-8" data-line-number="8">             <span class="dt">data=</span>DT)</a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -40.765   7:49:18      0           0
##     2      -30.2657   7:49:19      1           0
##     3      -25.8227   7:49:19      1           1
##     4      -24.7277   7:49:19      1           1
##     5      -24.7203   7:49:19      1           1
##     6      -24.7202   7:49:19      1           1</code></pre>
<pre class="sourceCode r" id="cb8"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw">summary</span>(ans1)<span class="op">$</span>varcomp</a></code></pre>
<pre><code>##                         VarComp  VarCompSE    Zratio Constraint
## Name.Yield-Yield       3.718279  1.6959834 2.1924029   Positive
## Env.Yield-Yield       12.008450 12.2771178 0.9781164   Positive
## Env:Name.Yield-Yield   5.152643  1.4923912 3.4526091   Positive
## Env:Block.Yield-Yield  0.000000  0.1156675 0.0000000   Positive
## units.Yield-Yield      4.366189  0.6573086 6.6425245   Positive</code></pre>
<pre class="sourceCode r" id="cb10"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">(n.env &lt;-<span class="st"> </span><span class="kw">length</span>(<span class="kw">levels</span>(DT<span class="op">$</span>Env)))</a></code></pre>
<pre><code>## [1] 3</code></pre>
<pre class="sourceCode r" id="cb12"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">pin</span>(ans1, h2 <span class="op">~</span><span class="st"> </span>V1 <span class="op">/</span><span class="st"> </span>( V1 <span class="op">+</span><span class="st"> </span>(V3<span class="op">/</span>n.env) <span class="op">+</span><span class="st"> </span>(V5<span class="op">/</span>(<span class="dv">2</span><span class="op">*</span>n.env)) ) )</a></code></pre>
<pre><code>##     Estimate        SE
## h2 0.6032715 0.1344582</code></pre>
<p>Recently with markers becoming cheaper, thousand of markers can be run in the breeding materials. When markers are available, an special design is not neccesary to disect the additive genetic variance. The availability of the additive, dominance and epistatic relationship matrices allow us to estimate <span class="math inline">\(\sigma^2_A\)</span>, <span class="math inline">\(\sigma^2_D\)</span> and <span class="math inline">\(\sigma^2_I\)</span>, although given that A, D and E are not orthogonal the interpretation of models that fit more than A and D become cumbersome.</p>
<p>Assume you have a population (even unreplicated) in the field but in addition we have genetic markers. Now we can fit the model and estimate the genomic heritability that explains a portion of the additive genetic variance (with high marker density <span class="math inline">\(\sigma^2_A\)</span> = <span class="math inline">\(\sigma^2_g\)</span>)</p>
<pre class="sourceCode r" id="cb14"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">data</span>(DT_cpdata)</a>
<a class="sourceLine" id="cb14-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_cpdata</a>
<a class="sourceLine" id="cb14-3" data-line-number="3">GT &lt;-<span class="st"> </span>GT_cpdata</a>
<a class="sourceLine" id="cb14-4" data-line-number="4">MP &lt;-<span class="st"> </span>MP_cpdata</a>
<a class="sourceLine" id="cb14-5" data-line-number="5">DT<span class="op">$</span>idd &lt;-DT<span class="op">$</span>id; DT<span class="op">$</span>ide &lt;-DT<span class="op">$</span>id</a>
<a class="sourceLine" id="cb14-6" data-line-number="6">### look at the data</a>
<a class="sourceLine" id="cb14-7" data-line-number="7">A &lt;-<span class="st"> </span><span class="kw">A.mat</span>(GT) <span class="co"># additive relationship matrix</span></a>
<a class="sourceLine" id="cb14-8" data-line-number="8">D &lt;-<span class="st"> </span><span class="kw">D.mat</span>(GT) <span class="co"># dominance relationship matrix</span></a>
<a class="sourceLine" id="cb14-9" data-line-number="9">E &lt;-<span class="st"> </span><span class="kw">E.mat</span>(GT) <span class="co"># epistatic relationship matrix</span></a>
<a class="sourceLine" id="cb14-10" data-line-number="10">ans.ADE &lt;-<span class="st"> </span><span class="kw">mmer</span>(color<span class="op">~</span><span class="dv">1</span>, </a>
<a class="sourceLine" id="cb14-11" data-line-number="11">                 <span class="dt">random=</span><span class="op">~</span><span class="kw">vs</span>(id,<span class="dt">Gu=</span>A) <span class="op">+</span><span class="st"> </span><span class="kw">vs</span>(idd,<span class="dt">Gu=</span>D), </a>
<a class="sourceLine" id="cb14-12" data-line-number="12">                 <span class="dt">rcov=</span><span class="op">~</span>units,</a>
<a class="sourceLine" id="cb14-13" data-line-number="13">                 <span class="dt">data=</span>DT)</a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -123   7:49:21      0           0
##     2      -107.864   7:49:22      1           0
##     3      -103.867   7:49:22      1           0
##     4      -103.315   7:49:22      1           0
##     5      -103.294   7:49:23      2           0
##     6      -103.293   7:49:23      2           0</code></pre>
<pre class="sourceCode r" id="cb16"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">(<span class="kw">summary</span>(ans.ADE)<span class="op">$</span>varcomp)</a></code></pre>
<pre><code>##                       VarComp    VarCompSE   Zratio Constraint
## u:id.color-color  0.003662202 0.0012194130 3.003250   Positive
## u:idd.color-color 0.001820079 0.0007406216 2.457502   Positive
## units.color-color 0.002106929 0.0002864724 7.354736   Positive</code></pre>
<pre class="sourceCode r" id="cb18"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw">pin</span>(ans.ADE, h2 <span class="op">~</span><span class="st"> </span>(V1) <span class="op">/</span><span class="st"> </span>( V1<span class="op">+</span>V3) )</a></code></pre>
<pre><code>##     Estimate         SE
## h2 0.6347926 0.08840488</code></pre>
<pre class="sourceCode r" id="cb20"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw">pin</span>(ans.ADE, h2 <span class="op">~</span><span class="st"> </span>(V1<span class="op">+</span>V2) <span class="op">/</span><span class="st"> </span>( V1<span class="op">+</span>V2<span class="op">+</span>V3) )</a></code></pre>
<pre><code>##     Estimate         SE
## h2 0.7223783 0.05563774</code></pre>
<p>In the previous example we showed how to estimate the additive (<span class="math inline">\(\sigma^2_A\)</span>), dominance (<span class="math inline">\(\sigma^2_D\)</span>), and epistatic (<span class="math inline">\(\sigma^2_I\)</span>) variance components based on markers and estimate broad (<span class="math inline">\(H^2\)</span>) and narrow sense heritability (<span class="math inline">\(h^2\)</span>). Notice that we used the <code>vs()</code> function which indicates that the random effect inside the parenthesis (i.e. id, idd or ide) has a covariance matrix (A, D, or E), that will be specified in the Gu argument of the vs() function. Please DO NOT provide the inverse but the original covariance matrix.</p>
</div>
<div id="specifying-heterogeneous-variances-in-univariate-models" class="section level2">
<h2>2) Specifying heterogeneous variances in univariate models</h2>
<p>Very often in multi-environment trials, the assumption that genetic variance is the same across locations may be too naive. Because of that, specifying a general genetic component and a location specific genetic variance is the way to go.</p>
<p>We estimate variance components for <span class="math inline">\(GCA_2\)</span> and <span class="math inline">\(SCA\)</span> specifying the variance structure.</p>
<pre class="sourceCode r" id="cb22"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="kw">data</span>(DT_cornhybrids)</a>
<a class="sourceLine" id="cb22-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_cornhybrids</a>
<a class="sourceLine" id="cb22-3" data-line-number="3">DTi &lt;-<span class="st"> </span>DTi_cornhybrids</a>
<a class="sourceLine" id="cb22-4" data-line-number="4">GT &lt;-<span class="st"> </span>GT_cornhybrids</a>
<a class="sourceLine" id="cb22-5" data-line-number="5">### fit the model</a>
<a class="sourceLine" id="cb22-6" data-line-number="6">modFD &lt;-<span class="st"> </span><span class="kw">mmer</span>(Yield<span class="op">~</span><span class="dv">1</span>, </a>
<a class="sourceLine" id="cb22-7" data-line-number="7">               <span class="dt">random=</span><span class="op">~</span><span class="st"> </span><span class="kw">vs</span>(<span class="kw">at</span>(Location,<span class="kw">c</span>(<span class="st">&quot;3&quot;</span>,<span class="st">&quot;4&quot;</span>)),GCA2), </a>
<a class="sourceLine" id="cb22-8" data-line-number="8">               <span class="dt">rcov=</span> <span class="op">~</span><span class="st"> </span><span class="kw">vs</span>(<span class="kw">ds</span>(Location),units),</a>
<a class="sourceLine" id="cb22-9" data-line-number="9">               <span class="dt">data=</span>DT)</a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -190.104   7:49:24      1           0
##     2      -171.543   7:49:24      1           0
##     3      -165.319   7:49:25      2           0
##     4      -164.691   7:49:25      2           0
##     5      -164.684   7:49:26      3           0
##     6      -164.684   7:49:26      3           0</code></pre>
<pre class="sourceCode r" id="cb24"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw">summary</span>(modFD)</a></code></pre>
<pre><code>## ============================================================
##          Multivariate Linear Mixed Model fit by REML         
## **********************  sommer 4.0  ********************** 
## ============================================================
##          logLik      AIC      BIC Method Converge
## Value -164.6839 331.3677 335.3592     NR     TRUE
## ============================================================
## Variance-Covariance components:
##                     VarComp VarCompSE Zratio Constraint
## 3:GCA2.Yield-Yield    62.48     53.45  1.169   Positive
## 4:GCA2.Yield-Yield    97.99     79.56  1.232   Positive
## 1:units.Yield-Yield  216.82     30.77  7.047   Positive
## 2:units.Yield-Yield  216.82     30.77  7.047   Positive
## 3:units.Yield-Yield  493.05     77.27  6.381   Positive
## 4:units.Yield-Yield  711.98    111.63  6.378   Positive
## ============================================================
## Fixed effects:
##   Trait      Effect Estimate Std.Error t.value
## 1 Yield (Intercept)    138.1    0.9442   146.3
## ============================================================
## Groups and observations:
##        Yield
## 3:GCA2    20
## 4:GCA2    20
## ============================================================
## Use the '$' sign to access results and parameters</code></pre>
<p>In the previous example we showed how the <code>at()</code> function is used in the <code>mmer</code> solver. By using the <code>at</code> function you can specify that i.e. the GCA2 has a different variance in different Locations, in this case locations 3 and 4, but also a main GCA variance. This is considered a CS + DIAG (compound symmetry + diagonal) model.</p>
<p>In addition, other functions can be added on top to fit models with covariance structures, i.e. the Gu argument from the <code>vs()</code> function to indicate a covariance matrix (A, pedigree or genomic relationship matrix)</p>
<pre class="sourceCode r" id="cb26"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="kw">data</span>(DT_cornhybrids)</a>
<a class="sourceLine" id="cb26-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_cornhybrids</a>
<a class="sourceLine" id="cb26-3" data-line-number="3">DTi &lt;-<span class="st"> </span>DTi_cornhybrids</a>
<a class="sourceLine" id="cb26-4" data-line-number="4">GT &lt;-<span class="st"> </span>GT_cornhybrids</a>
<a class="sourceLine" id="cb26-5" data-line-number="5">GT[<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>]</a></code></pre>
<pre><code>##             A258       A634        A641        A680
## A258  2.23285528 -0.3504778 -0.04756856 -0.32239362
## A634 -0.35047780  1.4529169  0.45203869 -0.02293680
## A641 -0.04756856  0.4520387  1.96940221 -0.09896791
## A680 -0.32239362 -0.0229368 -0.09896791  1.65221984</code></pre>
<pre class="sourceCode r" id="cb28"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1">### fit the model</a>
<a class="sourceLine" id="cb28-2" data-line-number="2">modFD &lt;-<span class="st"> </span><span class="kw">mmer</span>(Yield<span class="op">~</span><span class="dv">1</span>, </a>
<a class="sourceLine" id="cb28-3" data-line-number="3">              <span class="dt">random=</span><span class="op">~</span><span class="st"> </span><span class="kw">vs</span>(<span class="kw">at</span>(Location,<span class="kw">c</span>(<span class="st">&quot;3&quot;</span>,<span class="st">&quot;4&quot;</span>)),GCA2,<span class="dt">Gu=</span>GT), </a>
<a class="sourceLine" id="cb28-4" data-line-number="4">              <span class="dt">rcov=</span> <span class="op">~</span><span class="st"> </span><span class="kw">vs</span>(<span class="kw">ds</span>(Location),units),</a>
<a class="sourceLine" id="cb28-5" data-line-number="5">              <span class="dt">data=</span>DT)</a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -191.286   7:49:27      1           0
##     2      -172.247   7:49:27      1           0
##     3      -165.948   7:49:28      2           0
##     4      -165.248   7:49:28      2           0
##     5      -165.23   7:49:29      3           0
##     6      -165.229   7:49:30      4           0
##     7      -165.229   7:49:30      4           0</code></pre>
<pre class="sourceCode r" id="cb30"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="kw">summary</span>(modFD)</a></code></pre>
<pre><code>## ============================================================
##          Multivariate Linear Mixed Model fit by REML         
## **********************  sommer 4.0  ********************** 
## ============================================================
##          logLik      AIC      BIC Method Converge
## Value -165.2286 332.4571 336.4486     NR     TRUE
## ============================================================
## Variance-Covariance components:
##                     VarComp VarCompSE Zratio Constraint
## 3:GCA2.Yield-Yield    26.64     26.16 1.0185   Positive
## 4:GCA2.Yield-Yield    37.51     37.78 0.9927   Positive
## 1:units.Yield-Yield  216.77     30.75 7.0489   Positive
## 2:units.Yield-Yield  216.77     30.75 7.0489   Positive
## 3:units.Yield-Yield  503.62     77.87 6.4673   Positive
## 4:units.Yield-Yield  738.86    114.17 6.4715   Positive
## ============================================================
## Fixed effects:
##   Trait      Effect Estimate Std.Error t.value
## 1 Yield (Intercept)    138.1    0.9147     151
## ============================================================
## Groups and observations:
##        Yield
## 3:GCA2    20
## 4:GCA2    20
## ============================================================
## Use the '$' sign to access results and parameters</code></pre>
</div>
<div id="using-the-pin-calculator" class="section level2">
<h2>3) Using the pin calculator</h2>
<p>Sometimes the user needs to calculate ratios or functions of specific variance-covariance components and obtain the standard error for such parameters. Examples of these are the genetic correlations, heritabilities, etc. Using the CPdata we will show how to estimate the heritability and the standard error using the pin function that uses the delta method to come up with these parameters. This can be extended for any linear combination of the variance components.</p>
<pre class="sourceCode r" id="cb32"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="kw">data</span>(DT_cpdata)</a>
<a class="sourceLine" id="cb32-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_cpdata</a>
<a class="sourceLine" id="cb32-3" data-line-number="3">GT &lt;-<span class="st"> </span>GT_cpdata</a>
<a class="sourceLine" id="cb32-4" data-line-number="4">MP &lt;-<span class="st"> </span>MP_cpdata</a>
<a class="sourceLine" id="cb32-5" data-line-number="5">### look at the data</a>
<a class="sourceLine" id="cb32-6" data-line-number="6">A &lt;-<span class="st"> </span><span class="kw">A.mat</span>(GT) <span class="co"># additive relationship matrix</span></a>
<a class="sourceLine" id="cb32-7" data-line-number="7">ans &lt;-<span class="st"> </span><span class="kw">mmer</span>(color<span class="op">~</span><span class="dv">1</span>, </a>
<a class="sourceLine" id="cb32-8" data-line-number="8">                <span class="dt">random=</span><span class="op">~</span><span class="kw">vs</span>(id,<span class="dt">Gu=</span>A), </a>
<a class="sourceLine" id="cb32-9" data-line-number="9">                <span class="dt">rcov=</span><span class="op">~</span>units,</a>
<a class="sourceLine" id="cb32-10" data-line-number="10">                <span class="dt">data=</span>DT)</a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -137.304   7:49:32      1           0
##     2      -115.507   7:49:32      1           0
##     3      -111.236   7:49:32      1           0
##     4      -110.755   7:49:33      2           0
##     5      -110.741   7:49:33      2           0
##     6      -110.741   7:49:33      2           0</code></pre>
<pre class="sourceCode r" id="cb34"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1">(<span class="kw">summary</span>(ans.ADE)<span class="op">$</span>varcomp)</a></code></pre>
<pre><code>##                       VarComp    VarCompSE   Zratio Constraint
## u:id.color-color  0.003662202 0.0012194130 3.003250   Positive
## u:idd.color-color 0.001820079 0.0007406216 2.457502   Positive
## units.color-color 0.002106929 0.0002864724 7.354736   Positive</code></pre>
<pre class="sourceCode r" id="cb36"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1"><span class="kw">pin</span>(ans, h2 <span class="op">~</span><span class="st"> </span>(V1) <span class="op">/</span><span class="st"> </span>( V1<span class="op">+</span>V2) )</a></code></pre>
<pre><code>##     Estimate         SE
## h2 0.6512157 0.06107574</code></pre>
<p>The same can be used for multivariate models. Please check the documentation of the <code>pin</code> function to see more examples.</p>
</div>
<div id="half-and-full-diallel-designs-use-of-the-overlay" class="section level2">
<h2>4) Half and full diallel designs (use of the overlay)</h2>
<p>When breeders are looking for the best single cross combinations, diallel designs have been by far the most used design in crops like maize. There are 4 types of diallel designs depending if reciprocate and self cross (omission of parents) are performed (full diallel with parents n^2; full diallel without parents n(n-1); half diallel with parents 1/2 * n(n+1); half diallel without parents 1/2 * n(n-1) ). In this example we will show a full dialle design (reciprocate crosses are performed) and half diallel designs (only one of the directions is performed).</p>
<p>In the first data set we show a full diallel among 40 lines from 2 heterotic groups, 20 in each. Therefore 400 possible hybrids are possible. We have pehnotypic data for 100 of them across 4 locations. We use the data available to fit a model of the form:</p>
<p><br></p>
<p><span class="math inline">\(y = X\beta + Zu_1 + Zu_2 + Zu_S + \epsilon\)</span></p>
<p><br></p>
<p>We estimate variance components for <span class="math inline">\(GCA_1\)</span>, <span class="math inline">\(GCA_2\)</span> and <span class="math inline">\(SCA\)</span> and use them to estimate heritability. Additionally BLUPs for GCA and SCA effects can be used to predict crosses.</p>
<pre class="sourceCode r" id="cb38"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="kw">data</span>(DT_cornhybrids)</a>
<a class="sourceLine" id="cb38-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_cornhybrids</a>
<a class="sourceLine" id="cb38-3" data-line-number="3">DTi &lt;-<span class="st"> </span>DTi_cornhybrids</a>
<a class="sourceLine" id="cb38-4" data-line-number="4">GT &lt;-<span class="st"> </span>GT_cornhybrids</a>
<a class="sourceLine" id="cb38-5" data-line-number="5"></a>
<a class="sourceLine" id="cb38-6" data-line-number="6">modFD &lt;-<span class="st"> </span><span class="kw">mmer</span>(Yield<span class="op">~</span>Location, </a>
<a class="sourceLine" id="cb38-7" data-line-number="7">               <span class="dt">random=</span><span class="op">~</span>GCA1<span class="op">+</span>GCA2<span class="op">+</span>SCA, </a>
<a class="sourceLine" id="cb38-8" data-line-number="8">               <span class="dt">rcov=</span><span class="op">~</span>units,</a>
<a class="sourceLine" id="cb38-9" data-line-number="9">               <span class="dt">data=</span>DT)</a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -149.436   7:49:34      0           0
##     2      -136.475   7:49:34      0           1
##     3      -132.852   7:49:35      1           1
##     4      -132.625   7:49:36      2           1
##     5      -132.596   7:49:36      2           1
##     6      -132.59   7:49:36      2           1
##     7      -132.589   7:49:37      3           1
##     8      -132.589   7:49:37      3           1</code></pre>
<pre class="sourceCode r" id="cb40"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1">(suma &lt;-<span class="st"> </span><span class="kw">summary</span>(modFD)<span class="op">$</span>varcomp)</a></code></pre>
<pre><code>##                      VarComp VarCompSE     Zratio Constraint
## GCA1.Yield-Yield    0.000000  16.50337  0.0000000   Positive
## GCA2.Yield-Yield    7.412226  18.94200  0.3913116   Positive
## SCA.Yield-Yield   187.560303  41.59428  4.5092817   Positive
## units.Yield-Yield 221.142463  18.14716 12.1860656   Positive</code></pre>
<pre class="sourceCode r" id="cb42"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1">Vgca &lt;-<span class="st"> </span><span class="kw">sum</span>(suma[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,<span class="dv">1</span>])</a>
<a class="sourceLine" id="cb42-2" data-line-number="2">Vsca &lt;-<span class="st"> </span>suma[<span class="dv">3</span>,<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb42-3" data-line-number="3">Ve &lt;-<span class="st"> </span>suma[<span class="dv">4</span>,<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb42-4" data-line-number="4">Va =<span class="st"> </span><span class="dv">4</span><span class="op">*</span>Vgca</a>
<a class="sourceLine" id="cb42-5" data-line-number="5">Vd =<span class="st"> </span><span class="dv">4</span><span class="op">*</span>Vsca</a>
<a class="sourceLine" id="cb42-6" data-line-number="6">Vg &lt;-<span class="st"> </span>Va <span class="op">+</span><span class="st"> </span>Vd</a>
<a class="sourceLine" id="cb42-7" data-line-number="7">(H2 &lt;-<span class="st"> </span>Vg <span class="op">/</span><span class="st"> </span>(Vg <span class="op">+</span><span class="st"> </span>(Ve)) )</a></code></pre>
<pre><code>## [1] 0.7790856</code></pre>
<pre class="sourceCode r" id="cb44"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1">(h2 &lt;-<span class="st"> </span>Va <span class="op">/</span><span class="st"> </span>(Vg <span class="op">+</span><span class="st"> </span>(Ve)) )</a></code></pre>
<pre><code>## [1] 0.02961832</code></pre>
<p>Don’t worry too much about the small h2 value, the data was simulated to be mainly dominance variance, therefore the Va was simulated extremely small leading to such value of narrow sense h2.</p>
<p>In this second data set we show a small half diallel with 7 parents crossed in one direction. n(n-1)/2 crosses are possible 7(6)/2 = 21 unique crosses. Parents appear as males or females indistictly. Each with two replications in a CRD. For a half diallel design a single GCA variance component for both males and females can be estimated and an SCA as well (<span class="math inline">\(\sigma^2_GCA\)</span> and <span class="math inline">\(\sigma^2_SCA\)</span> respectively), and BLUPs for GCA and SCA of the parents can be extracted. We would show first how to use it with the <code>mmer</code> function using the <code>overlay()</code> function. The specific model here is:</p>
<p><span class="math inline">\(y = X\beta + Zu_g + Zu_s + \epsilon\)</span></p>
<pre class="sourceCode r" id="cb46"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1"><span class="kw">data</span>(<span class="st">&quot;DT_halfdiallel&quot;</span>)</a>
<a class="sourceLine" id="cb46-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_halfdiallel</a>
<a class="sourceLine" id="cb46-3" data-line-number="3"><span class="kw">head</span>(DT)</a></code></pre>
<pre><code>##   rep geno male female     sugar
## 1   1   12    1      2 13.950509
## 2   2   12    1      2  9.756918
## 3   1   13    1      3 13.906355
## 4   2   13    1      3  9.119455
## 5   1   14    1      4  5.174483
## 6   2   14    1      4  8.452221</code></pre>
<pre class="sourceCode r" id="cb48"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1">DT<span class="op">$</span>femalef &lt;-<span class="st"> </span><span class="kw">as.factor</span>(DT<span class="op">$</span>female)</a>
<a class="sourceLine" id="cb48-2" data-line-number="2">DT<span class="op">$</span>malef &lt;-<span class="st"> </span><span class="kw">as.factor</span>(DT<span class="op">$</span>male)</a>
<a class="sourceLine" id="cb48-3" data-line-number="3">DT<span class="op">$</span>genof &lt;-<span class="st"> </span><span class="kw">as.factor</span>(DT<span class="op">$</span>geno)</a>
<a class="sourceLine" id="cb48-4" data-line-number="4">#### model using overlay</a>
<a class="sourceLine" id="cb48-5" data-line-number="5">modh &lt;-<span class="st"> </span><span class="kw">mmer</span>(sugar<span class="op">~</span><span class="dv">1</span>, </a>
<a class="sourceLine" id="cb48-6" data-line-number="6">             <span class="dt">random=</span><span class="op">~</span><span class="kw">vs</span>(<span class="kw">overlay</span>(femalef,malef)) </a>
<a class="sourceLine" id="cb48-7" data-line-number="7">             <span class="op">+</span><span class="st"> </span>genof,</a>
<a class="sourceLine" id="cb48-8" data-line-number="8">             <span class="dt">data=</span>DT)</a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -10.425   7:49:38      0           0
##     2      -6.487   7:49:38      0           0
##     3      -5.732   7:49:38      0           0
##     4      -5.67494   7:49:38      0           0
##     5      -5.67441   7:49:38      0           0</code></pre>
<pre class="sourceCode r" id="cb50"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1"><span class="kw">summary</span>(modh)<span class="op">$</span>varcomp</a></code></pre>
<pre><code>##                        VarComp VarCompSE   Zratio Constraint
## u:femalef.sugar-sugar 5.507899 3.5741151 1.541052   Positive
## genof.sugar-sugar     1.815784 1.3629575 1.332238   Positive
## units.sugar-sugar     3.117538 0.9626094 3.238632   Positive</code></pre>
<p>Notice how the <code>overlay()</code> argument makes the overlap of incidence matrices possible making sure that male and female are joint into a single random effect.</p>
</div>
<div id="genomic-selection" class="section level2">
<h2>5) Genomic selection</h2>
<p>In this section we will use wheat data from CIMMYT to show how is genomic selection performed. This is the case of prediction of specific individuals within a population. It basically uses a similar model of the form:</p>
<p><br></p>
<p><span class="math inline">\(y = X\beta + Zu + \epsilon\)</span></p>
<p><br></p>
<p>and takes advantage of the variance covariance matrix for the genotype effect known as the additive relationship matrix (A) and calculated using the <code>A.mat</code> function to establish connections among all individuals and predict the BLUPs for individuals that were not measured. The prediction accuracy depends on several factors such as the heritability (<span class="math inline">\(h^2\)</span>), training population used (TP), size of TP, etc.</p>
<pre class="sourceCode r" id="cb52"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1"><span class="kw">data</span>(DT_wheat)</a>
<a class="sourceLine" id="cb52-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_wheat</a>
<a class="sourceLine" id="cb52-3" data-line-number="3">GT &lt;-<span class="st"> </span>GT_wheat</a>
<a class="sourceLine" id="cb52-4" data-line-number="4"><span class="kw">colnames</span>(DT) &lt;-<span class="st"> </span><span class="kw">paste0</span>(<span class="st">&quot;X&quot;</span>,<span class="dv">1</span><span class="op">:</span><span class="kw">ncol</span>(DT))</a>
<a class="sourceLine" id="cb52-5" data-line-number="5">DT &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(DT);DT<span class="op">$</span>id &lt;-<span class="st"> </span><span class="kw">as.factor</span>(<span class="kw">rownames</span>(DT))</a>
<a class="sourceLine" id="cb52-6" data-line-number="6"><span class="co"># select environment 1</span></a>
<a class="sourceLine" id="cb52-7" data-line-number="7"><span class="kw">rownames</span>(GT) &lt;-<span class="st"> </span><span class="kw">rownames</span>(DT)</a>
<a class="sourceLine" id="cb52-8" data-line-number="8">K &lt;-<span class="st"> </span><span class="kw">A.mat</span>(GT) <span class="co"># additive relationship matrix</span></a>
<a class="sourceLine" id="cb52-9" data-line-number="9"><span class="kw">colnames</span>(K) &lt;-<span class="st"> </span><span class="kw">rownames</span>(K) &lt;-<span class="st"> </span><span class="kw">rownames</span>(DT)</a>
<a class="sourceLine" id="cb52-10" data-line-number="10"><span class="co"># GBLUP pedigree-based approach</span></a>
<a class="sourceLine" id="cb52-11" data-line-number="11"><span class="kw">set.seed</span>(<span class="dv">12345</span>)</a>
<a class="sourceLine" id="cb52-12" data-line-number="12">y.trn &lt;-<span class="st"> </span>DT</a>
<a class="sourceLine" id="cb52-13" data-line-number="13">vv &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">rownames</span>(DT),<span class="kw">round</span>(<span class="kw">nrow</span>(DT)<span class="op">/</span><span class="dv">5</span>))</a>
<a class="sourceLine" id="cb52-14" data-line-number="14">y.trn[vv,<span class="st">&quot;X1&quot;</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb52-15" data-line-number="15"><span class="kw">head</span>(y.trn)</a></code></pre>
<pre><code>##              X1          X2          X3         X4   id
## 775          NA -1.72746986 -1.89028479  0.0509159  775
## 2166 -0.2527028  0.40952243  0.30938553 -1.7387588 2166
## 2167  0.3418151 -0.64862633 -0.79955921 -1.0535691 2167
## 2465         NA  0.09394919  0.57046773  0.5517574 2465
## 3881         NA -0.28248062  1.61868192 -0.1142848 3881
## 3889  2.3360969  0.62647587  0.07353311  0.7195856 3889</code></pre>
<pre class="sourceCode r" id="cb54"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1">## GBLUP</a>
<a class="sourceLine" id="cb54-2" data-line-number="2">ans &lt;-<span class="st"> </span><span class="kw">mmer</span>(X1<span class="op">~</span><span class="dv">1</span>,</a>
<a class="sourceLine" id="cb54-3" data-line-number="3">            <span class="dt">random=</span><span class="op">~</span><span class="kw">vs</span>(id,<span class="dt">Gu=</span>K), </a>
<a class="sourceLine" id="cb54-4" data-line-number="4">            <span class="dt">rcov=</span><span class="op">~</span>units, </a>
<a class="sourceLine" id="cb54-5" data-line-number="5">            <span class="dt">data=</span>y.trn) <span class="co"># kinship based</span></a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -202.344   7:49:40      1           0
##     2      -198.717   7:49:40      1           0
##     3      -197.634   7:49:41      2           0
##     4      -197.51   7:49:42      3           0
##     5      -197.508   7:49:43      4           0
##     6      -197.508   7:49:44      5           0</code></pre>
<pre class="sourceCode r" id="cb56"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1">ans<span class="op">$</span>U<span class="op">$</span><span class="st">`</span><span class="dt">u:id</span><span class="st">`</span><span class="op">$</span>X1 &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(ans<span class="op">$</span>U<span class="op">$</span><span class="st">`</span><span class="dt">u:id</span><span class="st">`</span><span class="op">$</span>X1)</a>
<a class="sourceLine" id="cb56-2" data-line-number="2"><span class="kw">rownames</span>(ans<span class="op">$</span>U<span class="op">$</span><span class="st">`</span><span class="dt">u:id</span><span class="st">`</span><span class="op">$</span>X1) &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;id&quot;</span>,<span class="st">&quot;&quot;</span>,<span class="kw">rownames</span>(ans<span class="op">$</span>U<span class="op">$</span><span class="st">`</span><span class="dt">u:id</span><span class="st">`</span><span class="op">$</span>X1))</a>
<a class="sourceLine" id="cb56-3" data-line-number="3"><span class="kw">cor</span>(ans<span class="op">$</span>U<span class="op">$</span><span class="st">`</span><span class="dt">u:id</span><span class="st">`</span><span class="op">$</span>X1[vv,],DT[vv,<span class="st">&quot;X1&quot;</span>], <span class="dt">use=</span><span class="st">&quot;complete&quot;</span>)</a></code></pre>
<pre><code>## [1] 0.4885674</code></pre>
<pre class="sourceCode r" id="cb58"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1">## rrBLUP</a>
<a class="sourceLine" id="cb58-2" data-line-number="2">ans2 &lt;-<span class="st"> </span><span class="kw">mmer</span>(X1<span class="op">~</span><span class="dv">1</span>,</a>
<a class="sourceLine" id="cb58-3" data-line-number="3">             <span class="dt">random=</span><span class="op">~</span><span class="kw">vs</span>(<span class="kw">list</span>(GT)), </a>
<a class="sourceLine" id="cb58-4" data-line-number="4">             <span class="dt">rcov=</span><span class="op">~</span>units,</a>
<a class="sourceLine" id="cb58-5" data-line-number="5">             <span class="dt">data=</span>y.trn) <span class="co"># kinship based</span></a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -343.082   7:49:46      1           0
##     2      -243.965   7:49:47      2           0
##     3      -208.257   7:49:48      3           0
##     4      -197.982   7:49:48      3           0
##     5      -197.519   7:49:49      4           0
##     6      -197.508   7:49:49      4           0
##     7      -197.508   7:49:50      5           0</code></pre>
<pre class="sourceCode r" id="cb60"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1">u &lt;-<span class="st"> </span>GT <span class="op">%*%</span><span class="st"> </span><span class="kw">as.matrix</span>(ans2<span class="op">$</span>U<span class="op">$</span><span class="st">`</span><span class="dt">u:GT</span><span class="st">`</span><span class="op">$</span>X1) <span class="co"># BLUPs for individuals</span></a>
<a class="sourceLine" id="cb60-2" data-line-number="2"><span class="kw">rownames</span>(u) &lt;-<span class="st"> </span><span class="kw">rownames</span>(GT)</a>
<a class="sourceLine" id="cb60-3" data-line-number="3"><span class="kw">cor</span>(u[vv,],DT[vv,<span class="st">&quot;X1&quot;</span>]) <span class="co"># same correlation</span></a></code></pre>
<pre><code>## [1] 0.4885716</code></pre>
<pre class="sourceCode r" id="cb62"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1"><span class="co"># the same can be applied in multi-response models in GBLUP or rrBLUP</span></a></code></pre>
</div>
<div id="single-cross-prediction" class="section level2">
<h2>6) Single cross prediction</h2>
<p>When doing prediction of single cross performance the phenotype can be dissected in three main components, the general combining abilities (GCA) and specific combining abilities (SCA). This can be expressed with the same model analyzed in the diallel experiment mentioned before:</p>
<p><br></p>
<p><span class="math inline">\(y = X\beta + Zu_1 + Zu_2 + Zu_S + \epsilon\)</span></p>
<p><br></p>
<p>with:</p>
<p><br></p>
<p><span class="math inline">\(u_1\)</span> ~ N(0, <span class="math inline">\(K_1\)</span><span class="math inline">\(\sigma^2_u1\)</span>)</p>
<p><span class="math inline">\(u_2\)</span> ~ N(0, <span class="math inline">\(K_2\)</span><span class="math inline">\(\sigma^2_u2\)</span>)</p>
<p><span class="math inline">\(u_s\)</span> ~ N(0, <span class="math inline">\(K_3\)</span><span class="math inline">\(\sigma^2_us\)</span>)</p>
<p><br></p>
<p>And we can specify the K matrices. The main difference between this model and the full and half diallel designs is the fact that this model will include variance covariance structures in each of the three random effects (GCA1, GCA2 and SCA) to be able to predict the crosses that have not ocurred yet. We will use the data published by Technow et al. (2015) to show how to do prediction of single crosses.</p>
<pre class="sourceCode r" id="cb63"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" data-line-number="1"><span class="kw">data</span>(DT_technow)</a>
<a class="sourceLine" id="cb63-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_technow</a>
<a class="sourceLine" id="cb63-3" data-line-number="3">Md &lt;-<span class="st"> </span>Md_technow</a>
<a class="sourceLine" id="cb63-4" data-line-number="4">Mf &lt;-<span class="st"> </span>Mf_technow</a>
<a class="sourceLine" id="cb63-5" data-line-number="5">Ad &lt;-<span class="st"> </span>Ad_technow</a>
<a class="sourceLine" id="cb63-6" data-line-number="6">Af &lt;-<span class="st"> </span>Af_technow</a>
<a class="sourceLine" id="cb63-7" data-line-number="7"><span class="co"># RUN THE PREDICTION MODEL</span></a>
<a class="sourceLine" id="cb63-8" data-line-number="8">y.trn &lt;-<span class="st"> </span>DT</a>
<a class="sourceLine" id="cb63-9" data-line-number="9">vv1 &lt;-<span class="st"> </span><span class="kw">which</span>(<span class="op">!</span><span class="kw">is.na</span>(DT<span class="op">$</span>GY))</a>
<a class="sourceLine" id="cb63-10" data-line-number="10">vv2 &lt;-<span class="st"> </span><span class="kw">sample</span>(vv1, <span class="dv">100</span>)</a>
<a class="sourceLine" id="cb63-11" data-line-number="11">y.trn[vv2,<span class="st">&quot;GY&quot;</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb63-12" data-line-number="12">anss2 &lt;-<span class="st"> </span><span class="kw">mmer</span>(GY<span class="op">~</span><span class="dv">1</span>, </a>
<a class="sourceLine" id="cb63-13" data-line-number="13">               <span class="dt">random=</span><span class="op">~</span><span class="kw">vs</span>(dent,<span class="dt">Gu=</span>Ad) <span class="op">+</span><span class="st"> </span><span class="kw">vs</span>(flint,<span class="dt">Gu=</span>Af), </a>
<a class="sourceLine" id="cb63-14" data-line-number="14">               <span class="dt">rcov=</span><span class="op">~</span>units,</a>
<a class="sourceLine" id="cb63-15" data-line-number="15">               <span class="dt">data=</span>y.trn) </a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      93.142   7:50:2      9           0
##     2      135.18   7:50:12      19           0
##     3      145.517   7:50:20      27           0
##     4      147.085   7:50:28      35           0
##     5      147.178   7:50:36      43           0
##     6      147.184   7:50:45      52           0
##     7      147.184   7:50:54      61           0</code></pre>
<pre class="sourceCode r" id="cb65"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1"><span class="kw">summary</span>(anss2)<span class="op">$</span>varcomp</a></code></pre>
<pre><code>##                VarComp VarCompSE    Zratio Constraint
## u:dent.GY-GY  16.93639 2.6917284  6.292012   Positive
## u:flint.GY-GY 12.47174 2.3248074  5.364634   Positive
## units.GY-GY   16.75020 0.7662471 21.860045   Positive</code></pre>
<pre class="sourceCode r" id="cb67"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" data-line-number="1">zu1 &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="op">~</span>dent<span class="dv">-1</span>,y.trn) <span class="op">%*%</span><span class="st"> </span>anss2<span class="op">$</span>U<span class="op">$</span><span class="st">`</span><span class="dt">u:dent</span><span class="st">`</span><span class="op">$</span>GY</a>
<a class="sourceLine" id="cb67-2" data-line-number="2">zu2 &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="op">~</span>flint<span class="dv">-1</span>,y.trn) <span class="op">%*%</span><span class="st"> </span>anss2<span class="op">$</span>U<span class="op">$</span><span class="st">`</span><span class="dt">u:flint</span><span class="st">`</span><span class="op">$</span>GY</a>
<a class="sourceLine" id="cb67-3" data-line-number="3">u &lt;-<span class="st"> </span>zu1<span class="op">+</span>zu2<span class="op">+</span>anss2<span class="op">$</span>Beta[<span class="dv">1</span>,<span class="st">&quot;Estimate&quot;</span>]</a>
<a class="sourceLine" id="cb67-4" data-line-number="4"><span class="kw">cor</span>(u[vv2,], DT<span class="op">$</span>GY[vv2])</a></code></pre>
<pre><code>## [1] 0.8234584</code></pre>
<p>In the previous model we only used the GCA effects (GCA1 and GCA2) for practicity, altough it’s been shown that the SCA effect doesn’t actually help that much in increasing prediction accuracy and increase a lot the computation intensity required since the variance covariance matrix for SCA is the kronecker product of the variance covariance matrices for the GCA effects, resulting in a 10578x10578 matrix that increases in a very intensive manner the computation required.</p>
<p>A model without covariance structures would show that the SCA variance component is insignificant compared to the GCA effects. This is why including the third random effect doesn’t increase the prediction accuracy.</p>
</div>
<div id="spatial-modeling-using-the-2-dimensional-spline" class="section level2">
<h2>7) Spatial modeling (using the 2-dimensional spline)</h2>
<p>We will use the CPdata to show the use of 2-dimensional splines for accomodating spatial effects in field experiments. In early generation variety trials the availability of seed is low, which makes the use of unreplicated design a neccesity more than anything else. Experimental designs such as augmented designs and partially-replicated (p-rep) designs become every day more common this days.</p>
<p>In order to do a good job modeling the spatial trends happening in the field special covariance structures have been proposed to accomodate such spatial trends (i.e. autoregressive residuals; ar1). Unfortunately, some of these covariance structures make the modeling rather unstable. More recently other research groups have proposed the use of 2-dimensional splines to overcome such issues and have a more robust modeling of the spatial terms (Lee et al. 2013; Rodríguez-Álvarez et al. 2018).</p>
<p>In this example we assume an unreplicated population where row and range information is available which allows us to fit a 2 dimensional spline model.</p>
<pre class="sourceCode r" id="cb69"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" data-line-number="1"><span class="kw">data</span>(DT_cpdata)</a>
<a class="sourceLine" id="cb69-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_cpdata</a>
<a class="sourceLine" id="cb69-3" data-line-number="3">GT &lt;-<span class="st"> </span>GT_cpdata</a>
<a class="sourceLine" id="cb69-4" data-line-number="4">MP &lt;-<span class="st"> </span>MP_cpdata</a>
<a class="sourceLine" id="cb69-5" data-line-number="5">### mimic two fields</a>
<a class="sourceLine" id="cb69-6" data-line-number="6">A &lt;-<span class="st"> </span><span class="kw">A.mat</span>(GT)</a>
<a class="sourceLine" id="cb69-7" data-line-number="7">mix &lt;-<span class="st"> </span><span class="kw">mmer</span>(Yield<span class="op">~</span><span class="dv">1</span>,</a>
<a class="sourceLine" id="cb69-8" data-line-number="8">            <span class="dt">random=</span><span class="op">~</span><span class="kw">vs</span>(id, <span class="dt">Gu=</span>A) <span class="op">+</span></a>
<a class="sourceLine" id="cb69-9" data-line-number="9"><span class="st">              </span><span class="kw">vs</span>(Rowf) <span class="op">+</span></a>
<a class="sourceLine" id="cb69-10" data-line-number="10"><span class="st">              </span><span class="kw">vs</span>(Colf) <span class="op">+</span></a>
<a class="sourceLine" id="cb69-11" data-line-number="11"><span class="st">              </span><span class="kw">vs</span>(<span class="kw">spl2D</span>(Row,Col)),</a>
<a class="sourceLine" id="cb69-12" data-line-number="12">            <span class="dt">rcov=</span><span class="op">~</span><span class="kw">vs</span>(units),</a>
<a class="sourceLine" id="cb69-13" data-line-number="13">            <span class="dt">data=</span>DT)</a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -154.198   7:50:56      0           0
##     2      -152.064   7:50:57      1           0
##     3      -151.265   7:50:57      1           0
##     4      -151.202   7:50:58      2           0
##     5      -151.201   7:50:58      2           0</code></pre>
<pre class="sourceCode r" id="cb71"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" data-line-number="1"><span class="kw">summary</span>(mix)</a></code></pre>
<pre><code>## ============================================================
##          Multivariate Linear Mixed Model fit by REML         
## **********************  sommer 4.0  ********************** 
## ============================================================
##          logLik      AIC      BIC Method Converge
## Value -151.2011 304.4021 308.2938     NR     TRUE
## ============================================================
## Variance-Covariance components:
##                     VarComp VarCompSE Zratio Constraint
## u:id.Yield-Yield      783.4     319.3 2.4536   Positive
## u:Rowf.Yield-Yield    814.7     390.5 2.0863   Positive
## u:Colf.Yield-Yield    182.2     129.7 1.4053   Positive
## u:Row.Yield-Yield     513.6     694.7 0.7393   Positive
## u:units.Yield-Yield  2922.6     294.1 9.9368   Positive
## ============================================================
## Fixed effects:
##   Trait      Effect Estimate Std.Error t.value
## 1 Yield (Intercept)    132.1     8.791   15.03
## ============================================================
## Groups and observations:
##        Yield
## u:id     363
## u:Rowf    13
## u:Colf    36
## u:Row    168
## ============================================================
## Use the '$' sign to access results and parameters</code></pre>
<p>Notice that the job is done by the <code>spl2D()</code> function that takes the Row and Col information to fit a spatial kernel.</p>
</div>
<div id="multivariate-genetic-models-and-genetic-correlations" class="section level2">
<h2>8) Multivariate genetic models and genetic correlations</h2>
<p>Sometimes is important to estimate genetic variance-covariance among traits, multi-reponse models are very useful for such task. Let see an example with 3 traits (color, Yield, and Firmness) and a single random effect (genotype; id) although multiple effects can be modeled as well. We need to use a variance covariance structure for the random effect to be able to obtain the genetic covariance among traits.</p>
<pre class="sourceCode r" id="cb73"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" data-line-number="1"><span class="kw">data</span>(DT_cpdata)</a>
<a class="sourceLine" id="cb73-2" data-line-number="2">DT &lt;-<span class="st"> </span>DT_cpdata</a>
<a class="sourceLine" id="cb73-3" data-line-number="3">GT &lt;-<span class="st"> </span>GT_cpdata</a>
<a class="sourceLine" id="cb73-4" data-line-number="4">MP &lt;-<span class="st"> </span>MP_cpdata</a>
<a class="sourceLine" id="cb73-5" data-line-number="5">A &lt;-<span class="st"> </span><span class="kw">A.mat</span>(GT)</a>
<a class="sourceLine" id="cb73-6" data-line-number="6">ans.m &lt;-<span class="st"> </span><span class="kw">mmer</span>(<span class="kw">cbind</span>(Yield,color)<span class="op">~</span><span class="dv">1</span>,</a>
<a class="sourceLine" id="cb73-7" data-line-number="7">               <span class="dt">random=</span><span class="op">~</span><span class="st"> </span><span class="kw">vs</span>(id, <span class="dt">Gu=</span>A, <span class="dt">Gtc=</span><span class="kw">unsm</span>(<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb73-8" data-line-number="8">               <span class="op">+</span><span class="st"> </span><span class="kw">vs</span>(Rowf,<span class="dt">Gtc=</span><span class="kw">diag</span>(<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb73-9" data-line-number="9">               <span class="op">+</span><span class="st"> </span><span class="kw">vs</span>(Colf,<span class="dt">Gtc=</span><span class="kw">diag</span>(<span class="dv">2</span>)),</a>
<a class="sourceLine" id="cb73-10" data-line-number="10">               <span class="dt">rcov=</span><span class="op">~</span><span class="st"> </span><span class="kw">vs</span>(units, <span class="dt">Gtc=</span><span class="kw">unsm</span>(<span class="dv">2</span>)),</a>
<a class="sourceLine" id="cb73-11" data-line-number="11">               <span class="dt">data=</span>DT)</a></code></pre>
<pre><code>## iteration    LogLik     wall    cpu(sec)   restrained
##     1      -375.872   7:51:4      5           0
##     2      -291.932   7:51:9      10           0
##     3      -258.273   7:51:14      15           0
##     4      -253.459   7:51:18      19           0
##     5      -253.291   7:51:23      24           0
##     6      -253.278   7:51:28      29           0
##     7      -253.277   7:51:34      35           0
##     8      -253.277   7:51:39      40           0</code></pre>
<p>Now you can extract the BLUPs using the ‘randef’ function or simple accesing with the ‘$’ sign and pick ‘u.hat’. Also, genetic correlations and heritabilities can be calculated easily.</p>
<pre class="sourceCode r" id="cb75"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" data-line-number="1"><span class="kw">cov2cor</span>(ans.m<span class="op">$</span>sigma<span class="op">$</span><span class="st">`</span><span class="dt">u:id</span><span class="st">`</span>)</a></code></pre>
<pre><code>##           Yield     color
## Yield 1.0000000 0.1234441
## color 0.1234441 1.0000000</code></pre>
</div>
<div id="final-remarks" class="section level2">
<h2>9) Final remarks</h2>
<p>Keep in mind that sommer uses direct inversion (DI) algorithm which can be very slow for large datasets. The package is focused in problems of the type p &gt; n (more random effect levels than observations) and models with dense covariance structures. For example, for experiment with dense covariance structures with low-replication (i.e. 2000 records from 1000 individuals replicated twice with a covariance structure of 1000x1000) sommer will be faster than MME-based software. Also for genomic problems with large number of random effect levels, i.e. 300 individuals (n) with 100,000 genetic markers (p). For highly replicated trials with small covariance structures or n &gt; p (i.e. 2000 records from 200 individuals replicated 10 times with covariance structure of 200x200) asreml or other MME-based algorithms will be much faster and we recommend you to opt for those software.</p>
</div>
<div id="literature" class="section level2">
<h2>Literature</h2>
<p>Covarrubias-Pazaran G. 2016. Genome assisted prediction of quantitative traits using the R package sommer. PLoS ONE 11(6):1-15.</p>
<p>Covarrubias-Pazaran G. 2018. Software update: Moving the R package sommer to multivariate mixed models for genome-assisted prediction. doi: <a href="https://doi.org/10.1101/354639" class="uri">https://doi.org/10.1101/354639</a></p>
<p>Bernardo Rex. 2010. Breeding for quantitative traits in plants. Second edition. Stemma Press. 390 pp.</p>
<p>Gilmour et al. 1995. Average Information REML: An efficient algorithm for variance parameter estimation in linear mixed models. Biometrics 51(4):1440-1450.</p>
<p>Henderson C.R. 1975. Best Linear Unbiased Estimation and Prediction under a Selection Model. Biometrics vol. 31(2):423-447.</p>
<p>Kang et al. 2008. Efficient control of population structure in model organism association mapping. Genetics 178:1709-1723.</p>
<p>Lee, D.-J., Durban, M., and Eilers, P.H.C. (2013). Efficient two-dimensional smoothing with P-spline ANOVA mixed models and nested bases. Computational Statistics and Data Analysis, 61, 22 - 37.</p>
<p>Lee et al. 2015. MTG2: An efficient algorithm for multivariate linear mixed model analysis based on genomic information. Cold Spring Harbor. doi: <a href="http://dx.doi.org/10.1101/027201" class="uri">http://dx.doi.org/10.1101/027201</a>.</p>
<p>Maier et al. 2015. Joint analysis of psychiatric disorders increases accuracy of risk prediction for schizophrenia, bipolar disorder, and major depressive disorder. Am J Hum Genet; 96(2):283-294.</p>
<p>Rodriguez-Alvarez, Maria Xose, et al. Correcting for spatial heterogeneity in plant breeding experiments with P-splines. Spatial Statistics 23 (2018): 52-71.</p>
<p>Searle. 1993. Applying the EM algorithm to calculating ML and REML estimates of variance components. Paper invited for the 1993 American Statistical Association Meeting, San Francisco.</p>
<p>Yu et al. 2006. A unified mixed-model method for association mapping that accounts for multiple levels of relatedness. Genetics 38:203-208.</p>
<p>Abdollahi Arpanahi R, Morota G, Valente BD, Kranis A, Rosa GJM, Gianola D. 2015. Assessment of bagging GBLUP for whole genome prediction of broiler chicken traits. Journal of Animal Breeding and Genetics 132:218-228.</p>
<p>Tunnicliffe W. 1989. On the use of marginal likelihood in time series model estimation. JRSS 51(1):15-27.</p>
</div>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
