<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Giovanny Covarrubias-Pazaran" />

<meta name="date" content="2025-04-01" />

<title>Quick start for the sommer package</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Quick start for the sommer package</h1>
<h4 class="author">Giovanny Covarrubias-Pazaran</h4>
<h4 class="date">2025-04-01</h4>



<p>The sommer package was developed to provide R users with a powerful
and reliable multivariate mixed model solver for different genetic and
non-genetic analyses in diploid and polyploid organisms. This package
allows the user to estimate variance components for a mixed model with
the advantages of specifying the variance-covariance structure of the
random effects, specifying heterogeneous variances, and obtaining other
parameters such as BLUPs, BLUEs, residuals, fitted values, variances for
fixed and random effects, etc. The core algorithms of the package are
coded in C++ using the Armadillo library to optimize dense matrix
operations common in the derect-inversion algorithms. Although the
vignette shows examples using the mme function with the default direct
inversion algorithm (henderson=FALSE) the Henderson’s approach can be
faster when the number of records surpasses the number of coefficients
to estimate and setting the henderson argument to TRUE can bring
significant speed ups.</p>
<p>The purpose of this quick start guide is to show the flexibility of
the package under certain common scenarios:</p>
<p><strong>SECTION 1: Introduction</strong></p>
<ol style="list-style-type: decimal">
<li>Background on mixed models</li>
<li>Background on covariance structures</li>
</ol>
<p><strong>SECTION 2: Different models enabled in sommer</strong></p>
<ol style="list-style-type: decimal">
<li>Univariate homogeneous variance models</li>
<li>Univariate heterogeneous variance models</li>
<li>Univariate unstructured variance models</li>
<li>Multivariate homogeneous variance models</li>
<li>Details on special functions for variance models
<ul>
<li>the major vsm() function for special variance models and its
auxiliars:</li>
<li>atm() specific levels heterogeneous variance structure</li>
<li>dsm() diagonal covariance structure</li>
<li>usm() unstructured covariance</li>
<li>csm() customized covariance structure</li>
<li>ism() function for main effects</li>
</ul></li>
<li>The specification of constraints in the variance-covariance
structures
<ul>
<li>unsm() unstructured constraint</li>
<li>fixm() fixed constraint</li>
</ul></li>
<li>Special functions for special models
<ul>
<li>Random regression models</li>
<li>Spatial models</li>
<li>Customized random effects</li>
</ul></li>
<li>Likelihood ratio tests</li>
<li>Final remarks</li>
</ol>
<p><strong>SECTION 3: The predict function</strong></p>
<ol style="list-style-type: decimal">
<li>Background on prediction</li>
<li>Predicting means</li>
</ol>
<div id="section-1-introduction" class="section level2">
<h2>SECTION 1: Introduction</h2>
<div id="background-on-mixed-models" class="section level3">
<h3>1) Background on mixed models</h3>
<p>The core of the package is the <code>mme</code> function which solves
the mixed model equations. The functions are an interface to call the
<code>NR</code> Direct-Inversion Newton-Raphson or Average Information
algorithms (Tunnicliffe 1989; Gilmour et al. 1995; Lee et al. 2016).
From version 2.0, sommer can handle multivariate models. Following Maier
et al. (2015), the multivariate (and by extension the univariate) mixed
model implemented has the form:</p>
<p><br></p>
<p><span class="math inline">\(y_1 = X_1\beta_1 + Z_1u_1 +
\epsilon_1\)</span></p>
<p><span class="math inline">\(y_2 = X_2\beta_2 + Z_2u_2 +
\epsilon_2\)</span></p>
<p>…</p>
<p><span class="math inline">\(y_i = X_i\beta_i + Z_iu_i +
\epsilon_i\)</span></p>
<p><br></p>
<p>where <span class="math inline">\(y_i\)</span> is a vector of trait
phenotypes, <span class="math inline">\(\beta_i\)</span> is a vector of
fixed effects, <span class="math inline">\(u_i\)</span> is a vector of
random effects for individuals and <span class="math inline">\(e_i\)</span> are residuals for trait ‘i’ (i = 1,
…, t). The random effects (<span class="math inline">\(u_1\)</span> …
<span class="math inline">\(u_i\)</span> and <span class="math inline">\(e_i\)</span>) are assumed to be normally
distributed with mean zero. X and Z are incidence matrices for fixed and
random effects respectively. The distribution of the multivariate
response and the phenotypic variance covariance (V) are:</p>
<p><br></p>
<p><span class="math inline">\(Y = X\beta + ZU + \epsilon_i\)</span></p>
<p><br></p>
<p>Y ~ MVN(<span class="math inline">\(X\beta\)</span>, V)</p>
<p><br></p>
<p><span class="math display">\[\mathbf{Y} = \left[\begin{array}
{r}
y_1 \\
y_2 \\
... \\
y_t \\
\end{array}\right]
\]</span></p>
<p><br></p>
<p><span class="math display">\[\mathbf{X} = \left[\begin{array}
{rrr}
X_1 &amp; 0 &amp; 0 \\
\vdots &amp; \ddots &amp; \vdots\\
0 &amp; 0 &amp; X_t \\
\end{array}\right]
\]</span></p>
<p><br></p>
<p><span class="math display">\[\mathbf{V} = \left[\begin{array}
{rrr}
Z_1 K{\sigma^2_{g_{1}}} Z_1&#39; + H{\sigma^2_{\epsilon_{1}}} &amp; ...
&amp; Z_1 K{\sigma_{g_{1,t}}} Z_t&#39; + H{\sigma_{\epsilon_{1,t}}} \\
\vdots &amp; \ddots &amp; \vdots\\
Z_1 K{\sigma_{g_{1,t}}} Z_t&#39; + H{\sigma_{\epsilon_{1,t}}} &amp; ...
&amp; Z_t K{\sigma^2_{g_{t}}} Z_t&#39; + H{\sigma^2_{\epsilon_{t}}} \\
\end{array}\right]
\]</span></p>
<p><br></p>
<p>where K is the relationship or covariance matrix for the kth random
effect (u=1,…,k), and H=I is an identity matrix or a partial identity
matrix for the residual term. The terms <span class="math inline">\(\sigma^2_{g_{i}}\)</span> and <span class="math inline">\(\sigma^2_{\epsilon_{i}}\)</span> denote the
genetic (or any of the kth random terms) and residual variance of trait
‘i’, respectively and <span class="math inline">\(\sigma_{g_{_{ij}}}\)</span> and <span class="math inline">\(\sigma_{\epsilon_{_{ij}}}\)</span> the genetic (or
any of the kth random terms) and residual covariance between traits ‘i’
and ‘j’ (i=1,…,t, and j=1,…,t). The algorithm implemented optimizes the
log likelihood:</p>
<p><br></p>
<p><span class="math inline">\(logL = 1/2 * ln(|V|) + ln(X&#39;|V|X) +
Y&#39;PY\)</span></p>
<p><br></p>
<p>where || is the determinant of a matrix. And the REML estimates are
updated using a Newton optimization algorithm of the form:</p>
<p><br></p>
<p><span class="math inline">\(\theta^{k+1} = \theta^{k} +
(H^{k})^{-1}*\frac{dL}{d\sigma^2_i}|\theta^k\)</span></p>
<p><br></p>
<p>Where <span class="math inline">\(\theta\)</span> is the vector of
variance components for random effects and covariance components among
traits, <span class="math inline">\(H^{-1}\)</span> is the inverse of
the Hessian matrix of second derivatives for the kth cycle, <span class="math inline">\(\frac{dL}{d\sigma^2_i}\)</span> is the vector of
first derivatives of the likelihood with respect to the
variance-covariance components. The Eigen decomposition of the
relationship matrix proposed by Lee and Van Der Werf (2016) was included
in the Newton-Raphson algorithm to improve time efficiency.
Additionally, the popular <code>vpredict()</code> function to estimate
standard errors for linear combinations of variance components
(i.e. heritabilities and genetic correlations) was added to the package
as well.</p>
<p>Please refer to the canonical papers listed in the Literature section
to check how the algorithms work. We have tested widely the methods to
make sure they provide the same solution when the likelihood behaves
well but for complex problems they might lead to slightly different
answers. If you have any concern please contact me at <a href="mailto:cova_ruber@live.com.mx" class="email">cova_ruber@live.com.mx</a>.</p>
<p>In the following section we will go in detail over several examples
on how to use mixed models in univariate and multivariate case and their
use in quantitative genetics.</p>
<p><br></p>
</div>
<div id="background-on-covariance-structures" class="section level3">
<h3>2) Background on covariance structures</h3>
<p>One of the major strenghts of linear mixed models is the flexibility
to specify variance-covariance structures at all levels. In general,
variance structures of mixed models can be seen as tensor (kronecker)
products of multiple variance-covariance stuctures. For example, a
multi-response model (i.e. 2 traits) where “g” individuals (i.e. 100
individuals) are tested in “e” treatments (i.e. 3 environments), the
variance-covariance for the random effect “individuals” can be seen as
the following multiplicative model:</p>
<p>T <span class="math inline">\(\otimes\)</span> G <span class="math inline">\(\otimes\)</span> A</p>
<p>where:</p>
<p><span class="math display">\[\mathbf{T} = \left[\begin{array}
{rr}
{\sigma^2_{g_{_{t1,t1}}}} &amp; {\sigma_{g_{_{t1,t2}}}} \\
{\sigma_{g_{_{t2,t1}}}} &amp; {\sigma^2_{g_{_{t2,t2}}}} \\
\end{array}\right]
\]</span></p>
<p>is the covariance structure for individuals among traits.</p>
<p><span class="math display">\[\mathbf{G} = \left[\begin{array}
{rrr}
{\sigma^2_{g_{_{e1,e1}}}} &amp; {\sigma_{g_{_{e1,e2}}}} &amp;
{\sigma_{g_{_{e1,e3}}}} \\
{\sigma_{g_{_{e2,e1}}}} &amp; {\sigma^2_{g_{_{e2,e2}}}} &amp;
{\sigma_{g_{_{e2,e3}}}} \\
{\sigma_{g_{_{e3,e1}}}} &amp; {\sigma_{g_{_{e3,e2}}}} &amp;
{\sigma^2_{g_{_{e3,e3}}}} \\
\end{array}\right]
\]</span></p>
<p>is the covariance structure for individuals among environments.</p>
<p>and <span class="math inline">\(A\)</span> is a square matrix
representing the covariance among the levels of the individuals (any
known relationship matrix).</p>
<p>The T and G covariance structures shown above are unknown matrices to
be estimated whereas A is known. The T and G matrices shown above are
called as unstructured (US) covariance matrices, although this type is
just one example from several covariance structures that the linear
mixed models enable. For example, other popular covariance structures
are:</p>
<p>Diagonal (DIAG) covariance structures</p>
<p><span class="math display">\[\mathbf{\Sigma} = \left[\begin{array}
{rrr}
{\sigma^2_{g_{_{e1,e1}}}} &amp; 0 &amp; 0 \\
\vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; {\sigma^2_{g_{_{ei,ei}}}} \\
\end{array}\right]
\]</span> Compound simmetry (CS) covariance structures</p>
<p><span class="math display">\[\mathbf{\Sigma} = \left[\begin{array}
{rrrr}
{\sigma^2_{g}} + {\sigma^2_{ge}} &amp; {\sigma^2_{g}} &amp;
{\sigma^2_{g}} &amp; {\sigma^2_{g}} \\
{\sigma^2_{g}} &amp; {\sigma^2_{g}} + {\sigma^2_{ge}} &amp;
{\sigma^2_{g}} &amp; {\sigma^2_{g}}\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
{\sigma^2_{g}} &amp; {\sigma^2_{g}} &amp; {\sigma^2_{g}} &amp;
{\sigma^2_{g}} + {\sigma^2_{ge}}\\
\end{array}\right]
\]</span></p>
<p>First order autoregressive (AR1) covariance structures</p>
<p><span class="math display">\[\mathbf{\Sigma} = \sigma^2
\left[\begin{array}
{rrrr}
1 &amp; {\rho} &amp; {\rho^2} &amp; {\rho^3} \\
{\rho} &amp; 1 &amp; {\rho} &amp; {\rho^2}\\
{\rho^2} &amp; {\rho} &amp; 1 &amp; {\rho} \\
{\rho^3} &amp; {\rho^2} &amp; {\rho}  &amp; 1  \\
\end{array}\right]
\]</span></p>
<p>or the already mentioned Unstructured (US) covariance structures</p>
<p><span class="math display">\[\mathbf{\Sigma} = \left[\begin{array}
{rrr}
{\sigma^2_{g_{_{e1,e1}}}} &amp; {\sigma_{g_{_{e1,e2}}}} &amp;
{\sigma_{g_{_{e1,e3}}}} \\
\vdots &amp; \ddots &amp; \vdots \\
{\sigma_{g_{_{e3,e1}}}} &amp; {\sigma_{g_{_{e3,e2}}}} &amp;
{\sigma^2_{g_{_{e3,e3}}}} \\
\end{array}\right]
\]</span></p>
<p>among others. Sommer has the capabilities to fit some of these
covariance structures in the mixed model machinery.</p>
</div>
</div>
<div id="section-2-different-models-enabled-in-sommer" class="section level2">
<h2>SECTION 2: Different models enabled in sommer</h2>
<div id="univariate-homogeneous-variance-models" class="section level3">
<h3>1) Univariate homogeneous variance models</h3>
<p>This type of model refers to single response models where a variable
of interest (i.e. genotypes) needs to be analyzed as interacting with a
2nd random effect (i.e. environments), but you assume that across
environments the genotypes have the same variance component. This is the
so-called compound symmetry (CS) model.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(sommer)</span></code></pre></div>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: MASS</code></pre>
<pre><code>## Loading required package: crayon</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="fu">data</span>(DT_example)</span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT_example</span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a><span class="do">## solving for r records</span></span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a>ans1c <span class="ot">&lt;-</span> <span class="fu">mme</span>(Yield<span class="sc">~</span>Env,</span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a>              <span class="at">random=</span> <span class="sc">~</span> Name <span class="sc">+</span> Env<span class="sc">:</span>Name,</span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a>              <span class="at">rcov=</span> <span class="sc">~</span> units,</span>
<span id="cb5-7"><a href="#cb5-7" tabindex="-1"></a>              <span class="at">data=</span>DT, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb5-8"><a href="#cb5-8" tabindex="-1"></a><span class="fu">summary</span>(ans1c)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                 VarComp VarCompSE   Zratio Constraint
## Name:mu:mu     3.681877 1.6909561 2.177394   Positive
## Env:Name:mu:mu 5.173062 1.4952313 3.459707   Positive
## units:mu:mu    4.366285 0.6470458 6.748031   Positive</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="do">## solving for c coefficients set henderson=TRUE</span></span></code></pre></div>
</div>
<div id="univariate-heterogeneous-variance-models" class="section level3">
<h3>2) Univariate heterogeneous variance models</h3>
<p>Very often in multi-environment trials, the assumption that the
genetic variance or the residual variance is the same across locations
may be too naive. Because of that, specifying a general genetic
component and a location specific genetic variance is the way to go.
This requires a CS+DIAG model (also called heterogeneous CS model).</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">data</span>(DT_example)</span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT_example</span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a>DT<span class="ot">=</span>DT[<span class="fu">with</span>(DT, <span class="fu">order</span>(Env)), ]</span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a>ans2c <span class="ot">&lt;-</span> <span class="fu">mme</span>(Yield<span class="sc">~</span>Env,</span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a>              <span class="at">random=</span> <span class="sc">~</span>Name <span class="sc">+</span> <span class="fu">vsm</span>(<span class="fu">dsm</span>(Env),<span class="fu">ism</span>(Name)),</span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a>              <span class="at">rcov=</span> <span class="sc">~</span> <span class="fu">vsm</span>(<span class="fu">dsm</span>(Env),<span class="fu">ism</span>(units)),</span>
<span id="cb8-8"><a href="#cb8-8" tabindex="-1"></a>              <span class="at">data=</span>DT, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-9"><a href="#cb8-9" tabindex="-1"></a><span class="fu">summary</span>(ans2c)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                             VarComp VarCompSE   Zratio Constraint
## Name:mu:mu                 2.962851 1.4962000 1.980251   Positive
## Env:Name:CA.2011:CA.2011  10.146369 4.5073271 2.251083   Positive
## Env:Name:CA.2012:CA.2012   1.877530 1.8697568 1.004158   Positive
## Env:Name:CA.2013:CA.2013   6.629152 2.5028114 2.648682   Positive
## Env:units:CA.2011:CA.2011  4.942450 1.5245057 3.242001   Positive
## Env:units:CA.2012:CA.2012  5.724963 1.3123015 4.362536   Positive
## Env:units:CA.2013:CA.2013  2.559880 0.6399685 4.000010   Positive</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="do">## solving for c coefficients set henderson=TRUE</span></span></code></pre></div>
<p>As you can see the special function <code>atm</code> or
<code>diag</code> can be used to indicate that there’s a different
variance for the genotypes in each environment. The same was done for
the residual. The difference between <code>atm</code> and
<code>diag</code> is that the <code>atm</code> function can be used to
specify the levels or specific environments where the variance is
different.</p>
</div>
<div id="unstructured-variance-models" class="section level3">
<h3>3) Unstructured variance models</h3>
<p>A more relaxed asumption than the CS+DIAG model is the unstructured
model (US) which assumes that among the levels of certain factor
(i.e. Environments) there’s a covariance struture of a second random
effect (i.e. Genotypes). This can be done in sommer using the
<code>usm(.)</code> function:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="fu">data</span>(DT_example)</span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT_example</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a>DT<span class="ot">=</span>DT[<span class="fu">with</span>(DT, <span class="fu">order</span>(Env)), ]</span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a>ans3c <span class="ot">&lt;-</span> <span class="fu">mme</span>(Yield<span class="sc">~</span>Env,</span>
<span id="cb11-6"><a href="#cb11-6" tabindex="-1"></a>             <span class="at">random=</span><span class="sc">~</span> <span class="fu">vsm</span>(<span class="fu">usm</span>(Env),<span class="fu">ism</span>(Name)),</span>
<span id="cb11-7"><a href="#cb11-7" tabindex="-1"></a>             <span class="at">rcov=</span><span class="sc">~</span><span class="fu">vsm</span>(<span class="fu">dsm</span>(Env),<span class="fu">ism</span>(units)), </span>
<span id="cb11-8"><a href="#cb11-8" tabindex="-1"></a>             <span class="at">data=</span>DT, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb11-9"><a href="#cb11-9" tabindex="-1"></a><span class="fu">summary</span>(ans3c)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                              VarComp VarCompSE    Zratio Constraint
## Env:Name:CA.2011:CA.2011  15.6650273 5.4207609 2.8898207   Positive
## Env:Name:CA.2011:CA.2012   6.1101144 2.4850458 2.4587533   Unconstr
## Env:Name:CA.2012:CA.2012   6.3845127 3.0659252 2.0824098   Positive
## Env:Name:CA.2011:CA.2013   4.5295385 1.8207704 2.4877044   Unconstr
## Env:Name:CA.2012:CA.2013   0.3931272 1.5233694 0.2580643   Unconstr
## Env:Name:CA.2013:CA.2013   8.5972326 2.4837409 3.4614048   Positive
## Env:units:CA.2011:CA.2011  4.9698392 1.5322454 3.2435008   Positive
## Env:units:CA.2012:CA.2012  5.6729708 1.3008225 4.3610645   Positive
## Env:units:CA.2013:CA.2013  2.5570946 0.6392829 3.9999423   Positive</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="do">## solving for c coefficients set henderson=TRUE</span></span></code></pre></div>
<p>As can be seen the <code>usm(Env)</code> indicates that the genotypes
(Name) can have a covariance structure among environments (Env).</p>
</div>
<div id="multivariate-homogeneous-variance-models" class="section level3">
<h3>4) Multivariate homogeneous variance models</h3>
<p>Currently there’s a great push for multi-response models. This is
motivated by the correlation that certain variables hide and that could
benefit in the prediction perspective. In sommer to specify multivariate
models the response requires the use of the <code>cbind()</code>
function in the response, and the <code>usm(trait)</code>,
<code>diag(trait)</code>, or <code>atm(trait)</code> functions in the
random part of the model.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="fu">data</span>(DT_example)</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT_example</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>DT2 <span class="ot">&lt;-</span> <span class="fu">stackTrait</span>(DT,<span class="at">traits =</span> <span class="fu">c</span>(<span class="st">&quot;Yield&quot;</span>,<span class="st">&quot;Weight&quot;</span>))<span class="sc">$</span>long</span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>DT2<span class="ot">=</span>DT2[<span class="fu">with</span>(DT2, <span class="fu">order</span>(trait)), ]</span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a>ans4c <span class="ot">&lt;-</span> <span class="fu">mme</span>(valueS <span class="sc">~</span> Env<span class="sc">:</span>trait,</span>
<span id="cb14-7"><a href="#cb14-7" tabindex="-1"></a>             <span class="at">random=</span> <span class="sc">~</span> <span class="fu">vsm</span>(<span class="fu">usm</span>(trait),<span class="fu">ism</span>(Name)),</span>
<span id="cb14-8"><a href="#cb14-8" tabindex="-1"></a>             <span class="at">rcov=</span> <span class="sc">~</span> <span class="fu">vsm</span>(<span class="fu">dsm</span>(trait),<span class="fu">ism</span>(units)),</span>
<span id="cb14-9"><a href="#cb14-9" tabindex="-1"></a>             <span class="at">data=</span>DT2, <span class="at">verbose =</span> F)</span>
<span id="cb14-10"><a href="#cb14-10" tabindex="-1"></a><span class="fu">summary</span>(ans4c)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                             VarComp  VarCompSE   Zratio Constraint
## trait:Name:Weight:Weight  0.2813217 0.08054357 3.492789   Positive
## trait:Name:Weight:Yield   0.3177637 0.07457957 4.260733   Unconstr
## trait:Name:Yield:Yield    0.2448029 0.07278135 3.363540   Positive
## trait:units:Weight:Weight 0.3586951 0.04189443 8.561882   Positive
## trait:units:Yield:Yield   0.3725767 0.04331247 8.602066   Positive</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="do">## to solve for c coefficients set henderson=TRUE</span></span></code></pre></div>
<p>You may notice that we have added the <code>usm(trait)</code> behind
the random effects. This is to indicate the structure that should be
assumed in the multivariate model. The <code>diag(trait)</code> used
behind a random effect (i.e. Name) indicates that for the traits modeled
(Yield and Weight) there’s no covariance component and should not be
estimated, whereas <code>usm(trait)</code> assumes that for such a
random effect, there’s a covariance component to be estimated
(i.e. covariance between Yield and Weight for the random effect Name).
The same applies for the residual part (rcov).</p>
<p>Any number of random effects can be specified with different
structures.</p>
</div>
<div id="details-on-special-functions-for-variance-models" class="section level3">
<h3>5) Details on special functions for variance models</h3>
<div id="the-vsm-function-for-special-variance-models-and-its-auxiliaries" class="section level4">
<h4>the vsm() function for special variance models and its
auxiliaries</h4>
<p>The sommer function <code>vsm()</code> allows constructing complex
variance models that are passed to the <code>mme()</code> function which
constitutes one of the most important features of the sommer package.
The specification of the <code>vsm()</code> function has the form:</p>
<p><code>random=~vsm(..., Gu)</code></p>
<p>The idea is that the <code>vsm()</code> function reflects the special
variance structure that each random effect could have in the matrix
notation:</p>
<p><span class="math inline">\(var(u) = T \bigotimes E \bigotimes ...
\bigotimes A\)</span></p>
<p>where the … argument in the <code>vsm()</code> function is used to
specify the kronecker products from all matrices that form the variance
for the random effect , where the auxiliary functions
<code>dsm()</code>, <code>usm()</code>, <code>csm()</code>,
<code>atm()</code>, <code>ism</code>, can be used to define such
structured variance structures with intial theta values and constraints.
The idea is that a variance model for a random effect x
(i.e. individuals) might require a more flexible model than just:</p>
<p><code>random=~x</code></p>
<p>For example, if individuals are tested in different time-points and
environments, we can assume a different variance and covariance
components among the individuals in the different environment-timepoint
combinations. An example of variance structure of the type:</p>
<p><span class="math inline">\(var(u) = T \bigotimes E \bigotimes S
\bigotimes A\)</span></p>
<p>would be specified in the <code>vsm()</code> function as:</p>
<p><code>random=~vsm(usm(e),usm(s), ism(x), Gu=A)</code></p>
<p>where the <code>e</code> would be a column vector in a data frame for
the environments, <code>s</code> a column vector in the dataframe for
the time points, <code>x</code> is the vector in the datrame for the
identifier of individuals, <code>A</code> is a known square variance
covariance matrix among individuals (usually an identity matrix; default
if not specified), and T is a square matrices with as many rows and
columns as the number of traits that specifies the trait covariance
structure.</p>
<p>The auxiliary functions to build the variance models for the random
effect are: + dsm() diagonal covariance structure + usm() unstructured
covariance + atm() specific levels heterogeneous variance structure +
ism() identity variance structure + csm() customized covariance
structure</p>
</div>
<div id="the-vsm-function-for-special-variance-models-and-its-auxiliaries-1" class="section level4">
<h4>the vsm() function for special variance models and its
auxiliaries</h4>
<p>The sommer function <code>vsm()</code> allows constructing complex
variance models that are passed to the <code>mme()</code> function which
constitutes one of the most important features of the sommer package.
The specification of the <code>vsm()</code> function has the form:</p>
<p><code>random=~vsm(..., Gu)</code></p>
<p>where the different variance structures are input as before but the
constraints are specified within the auxiliar function with the argument
theta and thetaC.</p>
</div>
<div id="dsm-and-dsm-to-specify-a-diagonal-diag-covariance-structures" class="section level4">
<h4>dsm() and dsm() to specify a diagonal (DIAG) covariance
structures</h4>
<p>A diagonal covariance structure looks like this:</p>
<p><span class="math display">\[\mathbf{\Sigma} = \left[\begin{array}
{rrr}
{\sigma^2_{g_{_{e1,e1}}}} &amp; 0 &amp; 0 \\
\vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; {\sigma^2_{g_{_{ei,ei}}}} \\
\end{array}\right]
\]</span> Considering an example for one random effect (g; indicating
i.e. individuals) evaluated in different treatment levels (e; indicating
i.e. the different treatments) the model would look like:</p>
<p><code>random=~vsm(dsm(e),ism(g))</code></p>
</div>
<div id="usm-and-usm-to-specify-an-unstructured-us-covariance" class="section level4">
<h4>usm() and usm() to specify an unstructured (US) covariance</h4>
<p>An unstructured covariance looks like this:</p>
<p><span class="math display">\[\mathbf{G} = \left[\begin{array}
{rrr}
{\sigma^2_{g_{_{e1,e1}}}} &amp; {\sigma_{g_{_{e1,e2}}}} &amp;
{\sigma_{g_{_{e1,e3}}}} \\
{\sigma_{g_{_{e2,e1}}}} &amp; {\sigma^2_{g_{_{e2,e2}}}} &amp;
{\sigma_{g_{_{e2,e3}}}} \\
{\sigma_{g_{_{e3,e1}}}} &amp; {\sigma_{g_{_{e3,e2}}}} &amp;
{\sigma^2_{g_{_{e3,e3}}}} \\
\end{array}\right]
\]</span></p>
<p>Considering same example for one random effect (g; indicating
i.e. individuals) evaluated in different treatment levels (e; indicating
i.e. the different treatments) the model would look like:</p>
<p><code>random=~vsm(usm(e),ism(g))</code></p>
</div>
<div id="atm-and-atc-to-specify-a-level-specific-heterogeneous-variance" class="section level4">
<h4>atm() and atc() to specify a level-specific heterogeneous
variance</h4>
<p>A diagonal covariance structure for specific levels of the second
random effect looks like this:</p>
<p><span class="math display">\[\mathbf{\Sigma} = \left[\begin{array}
{rrr}
{\sigma^2_{g_{_{e1,e1}}}} &amp; 0 &amp; 0 \\
\vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; {\sigma^2_{g_{_{ei,ei}}}} \\
\end{array}\right]
\]</span></p>
<p>Considering the same example for one random effect (g; indicating
i.e. individuals) evaluated in different treatment levels (e; indicating
i.e. the different treatments A,B,C) the model would look like:</p>
<p><code>random=~vsm(atc(e,c(&quot;A&quot;,&quot;B&quot;)),ism(g))</code></p>
<p>where the variance component for g is only fitted at levels A and
B.</p>
</div>
<div id="csm-and-csm-to-specify-a-level-specific-variance-covariance-structure" class="section level4">
<h4>csm() and csm() to specify a level-specific variance-covariance
structure</h4>
<p>A customized covariance structure for specific levels of the second
random effect (variance and covariances) looks i.e. like this:</p>
<p><span class="math display">\[\mathbf{\Sigma} = \left[\begin{array}
{rrr}
{\sigma^2_{g_{_{e1,e1}}}} &amp; {\sigma_{g_{_{e1,e2}}}} &amp; 0 \\
\vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; {\sigma^2_{g_{_{ei,ei}}}} \\
\end{array}\right]
\]</span></p>
<p>Considering same example for one random effect (g; indicating
i.e. individuals) evaluated in different treatment levels (e; indicating
i.e. the different treatments A,B,C) the model would look like:</p>
<p><code>random=~vsm(csm(e,mm=c(&quot;A&quot;,&quot;B&quot;)),ism(g))</code></p>
<p>where <code>mm</code> indicates which variance and covariance
components are estimated for <code>g</code>.</p>
</div>
</div>
<div id="the-specification-of-multi-trait-constraints-in-the-variance-components-for-the-vsm-function-gtc-argument" class="section level3">
<h3>6) The specification of multi-trait constraints in the variance
components for the vsm function (Gtc argument)</h3>
<p>One of the major strengths of sommer is its extreme flexibility to
specify variance-covariance structures in the multi-trait framework.
Since sommer 4.4 this is easily achieved by the use of the
<code>thetaC</code> argument available in any of the special functions
for variance structures. The <code>thetaC</code> argument expects a
matrix of constraints for the variance-covariance components for the
random effect filled with numbers according to the following rules:</p>
<ul>
<li>0: parameter not to be estimated</li>
<li>1: estimated and constrained to be positive</li>
<li>2: estimated and unconstrained</li>
<li>3: not to be estimated but fixed value provided in
<code>Gti</code></li>
</ul>
<p>Some useful functions to specify quickly the contraint matrices are
<code>unsm()</code> for unstructured, <code>fixm()</code> for fixed
constraint, and <code>fcm()</code> for fixed effect constraints.</p>
<p>Consider a multi-trait model with 4 traits (y1,…,y4) and 1 random
effect (u) and 1 fixed effect (x)</p>
<p><code>fixed=valueS~trait</code></p>
<p><code>random= ~vsm(csm(trait, thetaC=?), ism(u))</code></p>
<p>The constraint for the 4 x 4 matrix of variance covariance components
to be estimated can be an:</p>
<ol style="list-style-type: lower-alpha">
<li>unstructured</li>
</ol>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="co"># csm(trait, thetaC=unsm(4))</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a><span class="co"># # or just</span></span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a><span class="co"># usm(trait)</span></span></code></pre></div>
<ol start="3" style="list-style-type: lower-alpha">
<li>fixed (variance or covariance components indicated with a 3 are
considered fixed and values are provided in the Gti argument)</li>
</ol>
<p><code>random= ~vsm( csm(trait, thetaC=fixm(4)), ism(u) )</code></p>
</div>
<div id="special-functions-for-special-models" class="section level3">
<h3>7) Special functions for special models</h3>
<div id="random-regression-models" class="section level4">
<h4>Random regression models</h4>
<p>In order to fit random regression models the user can use the
<code>leg()</code> function to fit Legendre polynomials. This can be
combined with other special covariance structures such as
<code>dsm() / dsm()</code>, <code>usm() / usm()</code>, etc.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="fu">library</span>(orthopolynom)</span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a><span class="fu">data</span>(DT_legendre)</span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT_legendre</span>
<span id="cb18-4"><a href="#cb18-4" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" tabindex="-1"></a>mRR2c<span class="ot">&lt;-</span><span class="fu">mme</span>(Y<span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Xf</span>
<span id="cb18-6"><a href="#cb18-6" tabindex="-1"></a>           , <span class="at">random=</span><span class="sc">~</span> <span class="fu">vsm</span>(<span class="fu">usm</span>(<span class="fu">leg</span>(X,<span class="dv">1</span>)),<span class="fu">ism</span>(SUBJECT))</span>
<span id="cb18-7"><a href="#cb18-7" tabindex="-1"></a>           , <span class="at">rcov=</span><span class="sc">~</span><span class="fu">vsm</span>(<span class="fu">ism</span>(units))</span>
<span id="cb18-8"><a href="#cb18-8" tabindex="-1"></a>           , <span class="at">data=</span>DT, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb18-9"><a href="#cb18-9" tabindex="-1"></a><span class="fu">summary</span>(mRR2c)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                       VarComp VarCompSE   Zratio Constraint
## X:SUBJECT:leg0:leg0 2.5782970 0.6717247 3.838324   Positive
## X:SUBJECT:leg0:leg1 0.4765448 0.2394980 1.989765   Unconstr
## X:SUBJECT:leg1:leg1 0.3497299 0.2183232 1.601891   Positive
## units:mu:mu         2.6912229 0.3825201 7.035506   Positive</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="do">## to solve for c coefficients set henderson=TRUE</span></span></code></pre></div>
<p>Here, a numeric covariate X is used to explain the trajectory of the
SUBJECTs and combined with an unstructured covariance matrix. The
details can be found in the theory.</p>
</div>
<div id="spatial-models-using-the-2-dimensional-spline" class="section level4">
<h4>Spatial models (using the 2-dimensional spline)</h4>
<p>We will use the CPdata to show the use of 2-dimensional splines for
accomodating spatial effects in field experiments. In early generation
variety trials the availability of seed is low, which makes the use of
an unreplicated design a neccesity more than anything else. Experimental
designs such as augmented designs and partially-replicated (p-rep)
designs have become more common these days.</p>
<p>In order to do a good job modeling the spatial trends happening in
the field, special covariance structures have been proposed to
accomodate such spatial trends (i.e. autoregressive residuals; ar1).
Unfortunately, some of these covariance structures make the modeling
rather unstable. More recently other research groups have proposed the
use of 2-dimensional splines to overcome such issues and have a more
robust modeling of the spatial terms (Lee et al. 2013; Rodríguez-Álvarez
et al. 2018).</p>
<p>In this example we assume an unreplicated population where row and
range information is available which allows usm to fit a 2 dimensional
spline model.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">data</span>(DT_cpdata)</span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT_cpdata</span>
<span id="cb21-3"><a href="#cb21-3" tabindex="-1"></a>GT <span class="ot">&lt;-</span> GT_cpdata</span>
<span id="cb21-4"><a href="#cb21-4" tabindex="-1"></a>MP <span class="ot">&lt;-</span> MP_cpdata</span>
<span id="cb21-5"><a href="#cb21-5" tabindex="-1"></a><span class="do">### mimic two fields</span></span>
<span id="cb21-6"><a href="#cb21-6" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">A.mat</span>(GT)</span>
<span id="cb21-7"><a href="#cb21-7" tabindex="-1"></a>mix <span class="ot">&lt;-</span> <span class="fu">mme</span>(Yield<span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb21-8"><a href="#cb21-8" tabindex="-1"></a>            <span class="at">random=</span><span class="sc">~</span><span class="fu">vsm</span>(<span class="fu">ism</span>(id), <span class="at">Gu=</span>A) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" tabindex="-1"></a>              Rowf <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" tabindex="-1"></a>              Colf <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" tabindex="-1"></a>              <span class="fu">spl2Dc</span>(Row,Col),</span>
<span id="cb21-12"><a href="#cb21-12" tabindex="-1"></a>            <span class="at">rcov=</span><span class="sc">~</span>units, <span class="at">nIters=</span><span class="dv">10</span>,</span>
<span id="cb21-13"><a href="#cb21-13" tabindex="-1"></a>            <span class="at">data=</span>DT,<span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-14"><a href="#cb21-14" tabindex="-1"></a><span class="fu">summary</span>(mix)</span></code></pre></div>
<pre><code>## ============================================================
##          Multivariate Linear Mixed Model fit by REML         
## **********************  sommer 4.4  ********************** 
## ============================================================
##          logLik      AIC      BIC Method Converge
## Value -151.2011 304.4021 308.2938     AI     TRUE
## ============================================================
## Variance-Covariance components:
##                     VarComp VarCompSE Zratio Constraint
## id:A:mu:mu            783.4     319.3 2.4536   Positive
## Rowf:mu:mu            814.7     390.5 2.0863   Positive
## Colf:mu:mu            182.2     129.7 1.4053   Positive
## Row:Col:A:all:A:all   513.6     694.7 0.7393   Positive
## units:mu:mu          2922.6     294.1 9.9368   Positive
## ============================================================
## Fixed effects:
##             Estimate Std.Error t.value
## (Intercept)    132.1     8.791   15.03
## ============================================================
## Use the &#39;$&#39; sign to access results and parameters</code></pre>
<p>Notice that the job is done by the <code>spl2Dc()</code> function
that takes the <code>Row</code> and <code>Col</code> information to fit
a spatial kernel.</p>
</div>
<div id="customized-random-effects" class="section level4">
<h4>Customized random effects</h4>
<p>One of the most powerful features of sommer is the ability to provide
any customized matrix and estimate any random effect. For example:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">data</span>(DT_cpdata)</span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT_cpdata</span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a>GT <span class="ot">&lt;-</span> GT_cpdata</span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a>MP <span class="ot">&lt;-</span> MP_cpdata</span>
<span id="cb23-5"><a href="#cb23-5" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" tabindex="-1"></a><span class="do">#### look at the data and fit the model</span></span>
<span id="cb23-7"><a href="#cb23-7" tabindex="-1"></a>mix1 <span class="ot">&lt;-</span> <span class="fu">mme</span>(Yield<span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb23-8"><a href="#cb23-8" tabindex="-1"></a>              <span class="at">random=</span><span class="sc">~</span><span class="fu">vsm</span>(<span class="fu">ism</span>(GT)),</span>
<span id="cb23-9"><a href="#cb23-9" tabindex="-1"></a>              <span class="at">rcov=</span><span class="sc">~</span>units, <span class="at">nIters=</span><span class="dv">10</span>,</span>
<span id="cb23-10"><a href="#cb23-10" tabindex="-1"></a>              <span class="at">data=</span>DT,<span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>the matrix GT is provided as a random effect by encapsulating the
matrix in a list and provided in the <code>vsm()</code> function.</p>
</div>
</div>
<div id="likelihood-ratio-tests" class="section level3">
<h3>10) Likelihood ratio tests</h3>
<p>The Likelihood ratio test (LRT) is a good way to investigate the
significance of random effects or specific variance-covariance
components.</p>
<div id="testing-the-significance-of-a-variance-component" class="section level4">
<h4>10.1) Testing the significance of a variance component</h4>
<p>For example, imagine that a researcher would like to know if his
model improves when adding the effect of a spatial kernel to capture the
spatial trend in the field, his base model may look like this:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="fu">data</span>(DT_cpdata)</span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT_cpdata</span>
<span id="cb24-3"><a href="#cb24-3" tabindex="-1"></a>GT <span class="ot">&lt;-</span> GT_cpdata</span>
<span id="cb24-4"><a href="#cb24-4" tabindex="-1"></a>MP <span class="ot">&lt;-</span> MP_cpdata</span>
<span id="cb24-5"><a href="#cb24-5" tabindex="-1"></a><span class="do">### mimic two fields</span></span>
<span id="cb24-6"><a href="#cb24-6" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">A.mat</span>(GT)</span>
<span id="cb24-7"><a href="#cb24-7" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" tabindex="-1"></a>mix1 <span class="ot">&lt;-</span> <span class="fu">mme</span>(Yield<span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb24-9"><a href="#cb24-9" tabindex="-1"></a>            <span class="at">random=</span><span class="sc">~</span><span class="fu">vsm</span>(<span class="fu">ism</span>(id), <span class="at">Gu=</span>A) <span class="sc">+</span></span>
<span id="cb24-10"><a href="#cb24-10" tabindex="-1"></a>              Rowf <span class="sc">+</span></span>
<span id="cb24-11"><a href="#cb24-11" tabindex="-1"></a>              Colf,</span>
<span id="cb24-12"><a href="#cb24-12" tabindex="-1"></a>            <span class="at">rcov=</span><span class="sc">~</span>units, <span class="at">nIters=</span><span class="dv">3</span>,</span>
<span id="cb24-13"><a href="#cb24-13" tabindex="-1"></a>            <span class="at">data=</span>DT, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>And the model with the spatial kernel is the following:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a>mix2 <span class="ot">&lt;-</span> <span class="fu">mme</span>(Yield<span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a>            <span class="at">random=</span><span class="sc">~</span><span class="fu">vsm</span>(<span class="fu">ism</span>(id), <span class="at">Gu=</span>A) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" tabindex="-1"></a>              Rowf <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" tabindex="-1"></a>              Colf <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" tabindex="-1"></a>              <span class="fu">spl2Dc</span>(Row,Col),</span>
<span id="cb25-6"><a href="#cb25-6" tabindex="-1"></a>            <span class="at">rcov=</span><span class="sc">~</span>units, <span class="at">nIters=</span><span class="dv">10</span>,</span>
<span id="cb25-7"><a href="#cb25-7" tabindex="-1"></a>            <span class="at">data=</span>DT,<span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Then to test if the second model brings value let usm fit the
likelihood ratio test as follows:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a>lrt <span class="ot">&lt;-</span> <span class="fu">anova</span>(mix1, mix2)</span></code></pre></div>
<pre><code>## Likelihood ratio test for mixed models
## ==============================================================
##      Df      AIC      BIC     loLik   Chisq ChiDf  PrChisq
## mod2  6 304.4021 308.2938 -151.2011                       
## mod1  5 305.1825 309.0741 -151.5912 0.78039     1 0.37702 
## ==============================================================
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As can be seen the test turns out to not be very significant despite
the increase in the likelihood.</p>
</div>
</div>
</div>
<div id="section-3-the-predict-function" class="section level2">
<h2>SECTION 3: The predict function</h2>
<div id="background-on-prediction" class="section level3">
<h3>1) Background on prediction</h3>
<p>In a linear mixed model where y is an nx1 vector of observations, the
linear mixed model can be written as:</p>
<p><span class="math inline">\(y = X\tau + Zu + e =  W \beta +
e\)</span></p>
<p>where <span class="math inline">\(\tau\)</span> is a vector tx1 of
fixed effects, X is an nxt design matrix which associates observations
with the appropriate combinations of fixed effects, u is the qx1 vector
of random effects, Z is the nxq matrix which associates observations
with the appropriate random effects, and e is the nx1 vector of residual
errors. For shorthand W and <span class="math inline">\(\beta\)</span>
represent the combined design matrix and vector of efects, respectively.
It is assumed:</p>
<p><span class="math display">\[ \left[\begin{array}
{r}
u \\
e \\
\end{array}\right] = N(\left[\begin{array}
{r}
0 \\
0 \\
\end{array}\right] , \left[\begin{array}
{rr}
G{(\gamma)} &amp; 0 \\
0 &amp; R{(\phi)} \\
\end{array}\right])
\]</span></p>
<p>where the covariance matrices G and R for random effects and
residuals are functions of parameters <span class="math inline">\(\gamma\)</span> and <span class="math inline">\(\phi\)</span> respectively. The covariance matrix
of data can be written as:</p>
<p><span class="math inline">\(var(y) = \sigma^2
(ZGZ&#39;+R)\)</span></p>
<p>The variance parameters <span class="math inline">\(\gamma\)</span>
and <span class="math inline">\(\phi\)</span> are usually estimated by
maximum likelihood or REML (Patterson and Thompson, 1971).</p>
<p>The BLUP of a linear combination for known D, <span class="math inline">\(\gamma\)</span>, and <span class="math inline">\(\phi\)</span> is then:</p>
<p><span class="math display">\[\mathbf{D\overline{\beta}} =
\left[\begin{array}
{rr}
D_{\tau} &amp; D_u \\
\end{array}\right]  \left[\begin{array}
{r}
\overline{\tau} \\
\overline{u} \\
\end{array}\right] = {D \overline{\tau}} + {D_{u}\overline{u}}
\]</span> where <span class="math inline">\(\overline{\beta} = (\tau,
u)\)</span> is the solution of the mixed moel equations:</p>
<p><span class="math display">\[ \left[\begin{array}
{rr}
X^TR^{-1}X &amp; X^TR^{-1}Z  \\
Z^TR^{-1}X &amp; Z^TR^{-1}Z + G^{-1} \\
\end{array}\right]  \left[\begin{array}
{r}
\tau \\
u \\
\end{array}\right] = \left[\begin{array}
{r}
X^TR^{-1}y \\
Z^TR^{-1}X \\
\end{array}\right]
\]</span></p>
<p>These can also be written as <span class="math inline">\(C
\overline{\beta} = W^TR^{-1}y\)</span>. The <span class="math inline">\(\overline{\tau}\)</span> is the best linear
unbiased estimator (BLUE) of <span class="math inline">\(\tau\)</span>
and <span class="math inline">\(\overline{u}\)</span> is the best linear
unbiased predictor (BLUP) of <span class="math inline">\(u\)</span>,
this with variance <span class="math inline">\(var(\overline{\beta}-\beta)=C^{-1}\)</span>.
Consideration of the values required to form the confidence intervals
make it clear that is the prediction error variance (PEV or <span class="math inline">\(var(\overline{\beta}-\beta)\)</span>), rather than
the variance of the estimator <span class="math inline">\(var(\overline{\beta})\)</span> that is usually of
interest. The prediction error variance for a linear combination <span class="math inline">\(D\overline{\beta}\)</span> is then <span class="math inline">\(DC^{-1}D^T\)</span>. Since the variance parameters
are unknown, we replace the unknown variance parameters by their REML
estimates and use the empirical values.</p>
<p>The <code>predict()</code> function of the sommer package then builts
the <span class="math inline">\(C^{-1}\)</span> matrix from the mixed
model equations and the <span class="math inline">\(D\)</span> matrix of
linear combinations to obtain the PEV and SEs for the predictions. For
the means it uses the <span class="math inline">\(D\)</span> matrix of
linear combinations times the vector of required fixed and random
effects <span class="math inline">\(X\overline{\tau} + Z
\overline{u}\)</span> or <span class="math inline">\(D\overline{\beta}\)</span>, where the matrix D is
a linear combination of specific fixed and/or random effects from
matrices <span class="math inline">\(X\)</span> and/or <span class="math inline">\(Z\)</span>.</p>
</div>
<div id="predicting-means" class="section level3">
<h3>2) Predicting means</h3>
<p>The sommer package is equiped with a <code>predict()</code> function
that can be used to calculate means and standard errors for fixed and
random effects specified in the models fitted with the
<code>mme()</code> and <code>mme</code> functions. Using the yatesoats
dataset we will will fit some fixed and random effects.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="fu">library</span>(sommer)</span>
<span id="cb28-2"><a href="#cb28-2" tabindex="-1"></a><span class="fu">data</span>(DT_yatesoats)</span>
<span id="cb28-3"><a href="#cb28-3" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT_yatesoats</span>
<span id="cb28-4"><a href="#cb28-4" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">mme</span>(<span class="at">fixed=</span>Y <span class="sc">~</span> V <span class="sc">+</span> N <span class="sc">+</span> V<span class="sc">:</span>N,</span>
<span id="cb28-5"><a href="#cb28-5" tabindex="-1"></a>           <span class="at">random =</span> <span class="sc">~</span> B <span class="sc">+</span> B<span class="sc">:</span>MP,</span>
<span id="cb28-6"><a href="#cb28-6" tabindex="-1"></a>           <span class="at">rcov=</span><span class="sc">~</span>units,</span>
<span id="cb28-7"><a href="#cb28-7" tabindex="-1"></a>           <span class="at">data =</span> DT, <span class="at">verbose=</span><span class="cn">FALSE</span>)</span>
<span id="cb28-8"><a href="#cb28-8" tabindex="-1"></a><span class="fu">summary</span>(m3)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##              VarComp VarCompSE   Zratio Constraint
## B:mu:mu     214.4477 168.62790 1.271722   Positive
## B:MP:mu:mu  106.0508  67.83280 1.563415   Positive
## units:mu:mu 177.0883  37.34293 4.742217   Positive</code></pre>
<p>Now, the model can be used together with the <code>classify</code>
argument to obtain means for the <code>classify</code> argument. For
example, the model includes in the fixed formula the terms “V” for
variety, “N” for nitrogen treatments, and “V:N” for the interaction
between variety and nitrogen. The <code>classify</code> argument can be
used to specify the term for which the means are desired. In the
following example the means for the nitrogen treatments are obtained as
follows:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a>Dt <span class="ot">&lt;-</span> m3<span class="sc">$</span>Dtable; Dt</span></code></pre></div>
<pre><code>##     type               term include average
## 1  fixed                  V   FALSE   FALSE
## 2  fixed                  N   FALSE   FALSE
## 3  fixed                V:N   FALSE   FALSE
## 4 random    vsm( ism( B ) )   FALSE   FALSE
## 5 random vsm( ism( B:MP ) )   FALSE   FALSE</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="co"># first fixed effect just average</span></span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a>Dt[<span class="dv">1</span>,<span class="st">&quot;average&quot;</span>] <span class="ot">=</span> <span class="cn">TRUE</span></span>
<span id="cb32-3"><a href="#cb32-3" tabindex="-1"></a><span class="co"># second fixed effect include</span></span>
<span id="cb32-4"><a href="#cb32-4" tabindex="-1"></a>Dt[<span class="dv">2</span>,<span class="st">&quot;include&quot;</span>] <span class="ot">=</span> <span class="cn">TRUE</span></span>
<span id="cb32-5"><a href="#cb32-5" tabindex="-1"></a><span class="co"># third fixed effect include and average</span></span>
<span id="cb32-6"><a href="#cb32-6" tabindex="-1"></a>Dt[<span class="dv">3</span>,<span class="st">&quot;include&quot;</span>] <span class="ot">=</span> <span class="cn">TRUE</span></span>
<span id="cb32-7"><a href="#cb32-7" tabindex="-1"></a>Dt[<span class="dv">3</span>,<span class="st">&quot;average&quot;</span>] <span class="ot">=</span> <span class="cn">TRUE</span></span>
<span id="cb32-8"><a href="#cb32-8" tabindex="-1"></a>Dt</span></code></pre></div>
<pre><code>##     type               term include average
## 1  fixed                  V   FALSE    TRUE
## 2  fixed                  N    TRUE   FALSE
## 3  fixed                V:N    TRUE    TRUE
## 4 random    vsm( ism( B ) )   FALSE   FALSE
## 5 random vsm( ism( B:MP ) )   FALSE   FALSE</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a>pp<span class="ot">=</span><span class="fu">predict</span>(<span class="at">object=</span>m3, <span class="at">Dtable=</span>Dt, <span class="at">D=</span><span class="st">&quot;N&quot;</span>)</span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>pp<span class="sc">$</span>pvals</span></code></pre></div>
<pre><code>##       N predicted.value std.error
## 0     0        79.38889  7.174346
## 0.2 0.2        98.88889  7.174346
## 0.4 0.4       114.22222  7.174346
## 0.6 0.6       123.38889  7.174346</code></pre>
</div>
</div>
<div id="literature" class="section level2">
<h2>Literature</h2>
<p>Covarrubias-Pazaran G. 2016. Genome assisted prediction of
quantitative traits using the R package sommer. PLoS ONE 11(6):1-15.</p>
<p>Covarrubias-Pazaran G. 2018. Software update: Moving the R package
sommer to multivariate mixed models for genome-assisted prediction. doi:
<a href="https://doi.org/10.1101/354639" class="uri">https://doi.org/10.1101/354639</a></p>
<p>Bernardo Rex. 2010. Breeding for quantitative traits in plants.
Second edition. Stemma Press. 390 pp.</p>
<p>Gilmour et al. 1995. Average Information REML: An efficient algorithm
for variance parameter estimation in linear mixed models. Biometrics
51(4):1440-1450.</p>
<p>Henderson C.R. 1975. Best Linear Unbiased Estimation and Prediction
under a Selection Model. Biometrics vol. 31(2):423-447.</p>
<p>Kang et al. 2008. Efficient control of population structure in model
organism association mapping. Genetics 178:1709-1723.</p>
<p>Lee, D.-J., Durban, M., and Eilers, P.H.C. (2013). Efficient
two-dimensional smoothing with P-spline ANOVA mixed models and nested
bases. Computational Statistics and Data Analysis, 61, 22 - 37.</p>
<p>Lee et al. 2015. MTG2: An efficient algorithm for multivariate linear
mixed model analysis based on genomic information. Cold Spring Harbor.
doi: <a href="http://dx.doi.org/10.1101/027201" class="uri">http://dx.doi.org/10.1101/027201</a>.</p>
<p>Maier et al. 2015. Joint analysis of psychiatric disorders increases
accuracy of risk prediction for schizophrenia, bipolar disorder, and
major depressive disorder. Am J Hum Genet; 96(2):283-294.</p>
<p>Rodriguez-Alvarez, Maria Xose, et al. Correcting for spatial
heterogeneity in plant breeding experiments with P-splines. Spatial
Statistics 23 (2018): 52-71.</p>
<p>Searle. 1993. Applying the EM algorithm to calculating ML and REML
estimates of variance components. Paper invited for the 1993 American
Statistical Association Meeting, San Francisco.</p>
<p>Yu et al. 2006. A unified mixed-model method for association mapping
that accounts for multiple levels of relatedness. Genetics
38:203-208.</p>
<p>Tunnicliffe W. 1989. On the use of marginal likelihood in time series
model estimation. JRSS 51(1):15-27.</p>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
