# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

currentDateTime <- function() {
    .Call(`_sommer_currentDateTime`)
}

seqCpp <- function(a, b) {
    .Call(`_sommer_seqCpp`, a, b)
}

mat_to_vecCpp <- function(x, x2) {
    .Call(`_sommer_mat_to_vecCpp`, x, x2)
}

vec_to_cubeCpp <- function(x, g) {
    .Call(`_sommer_vec_to_cubeCpp`, x, g)
}

varCols <- function(x) {
    .Call(`_sommer_varCols`, x)
}

scaleCpp <- function(x) {
    .Call(`_sommer_scaleCpp`, x)
}

makeFull <- function(X) {
    .Call(`_sommer_makeFull`, X)
}

isIdentity_mat <- function(x) {
    .Call(`_sommer_isIdentity_mat`, x)
}

isIdentity_spmat <- function(x) {
    .Call(`_sommer_isIdentity_spmat`, x)
}

MNR <- function(Y, X, Gx, Z, K, R, Ge, GeI, ws, iters, tolpar, tolparinv, ai, pev, verbose, retscaled) {
    .Call(`_sommer_MNR`, Y, X, Gx, Z, K, R, Ge, GeI, ws, iters, tolpar, tolparinv, ai, pev, verbose, retscaled)
}

